Для начала проверим получилось доступпна ли нам видеокарта для обучения

In [1]:
import torch

print(torch.__version__)
print("CUDA:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else None)

2.3.1+cu121
CUDA: True
GPU: NVIDIA GeForce RTX 3050 Laptop GPU

Импортируем нужные библиотеки

In [2]:
import pandas as pd
from pathlib import Path
from PIL import Image
import shutil
from sklearn.model_selection import train_test_split
import os

Теперь мы должны привести датасет в нужный для нас формат. Разделим train на train и val. Достанем информацию из csv файлов и сделаем для каждой картинки txt файл, который будет ее описывать.

In [3]:
data_path = Path("data")

images_path = data_path / "train"
csv_path = data_path / "train_solution_bounding_boxes (1).csv"

output_path = Path("dataset")

labels_train = output_path / "labels/train"
labels_val = output_path / "labels/val"

images_train = output_path / "images/train"
images_val = output_path / "images/val"

for p in [labels_train, labels_val, images_train, images_val]:
    p.mkdir(parents=True, exist_ok=True)

Посмотрим как выглядит csv файл:

In [4]:
df = pd.read_csv(csv_path)
df.head()

             image        xmin        ymin        xmax        ymax
0   vid_4_1000.jpg  281.259045  187.035071  327.727931  223.225547
1  vid_4_10000.jpg   15.163531  187.035071  120.329957  236.430180
2  vid_4_10040.jpg  239.192475  176.764801  361.968162  236.430180
3  vid_4_10020.jpg  496.483358  172.363256  630.020260  231.539575
4  vid_4_10060.jpg   16.630970  186.546010  132.558611  238.386422

Мы видим координаты. Теперь мы должны достать их из csv и для каждого изображения создать отдельный txt файл такого вида:

0 0.5137481910502958 0.5520431146052631 0.17945007233727814 0.11711711710526315

Здесь первый 0 описывает класс, присутствующий на изображении, но т.к. у нас только 1 класс, то у нас в этой строке везде будет 0, другие же 4 числа - координаты, приведенные в нужный нам формат. Ниже представлена функция, которая это делает:

In [5]:
def convert(xmin, ymin, xmax, ymax, w, h):
    x_center = (xmin + xmax) / 2 / w
    y_center = (ymin + ymax) / 2 / h
    width = (xmax - xmin) / w
    height = (ymax - ymin) / h
    return x_center, y_center, width, height

Берем 20 процентов от train выборки и делаем из них валидационную выборку

In [6]:
images = df["image"].unique()

train_imgs, val_imgs = train_test_split(images, test_size=0.2, random_state=42)

Копируем изображения и создаем txt файлы нужного формата

In [7]:
def copy_images(img_list, split):
    for img_name in img_list:
        src = images_path / img_name
        dst = output_path / f"images/{split}" / img_name

        if src.exists():
            shutil.copy(src, dst)

copy_images(train_imgs, "train")
copy_images(val_imgs, "val")

In [8]:
def create_labels(img_list, split):
    for img_name in img_list:
        img_path = images_path / img_name

        if not img_path.exists():
            continue

        img = Image.open(img_path)
        w, h = img.size

        rows = df[df["image"] == img_name]

        label_file = output_path / f"labels/{split}" / (img_name.replace(".jpg", ".txt"))

        with open(label_file, "w") as f:
            for _, row in rows.iterrows():
                x, y, bw, bh = convert(
                    row["xmin"], row["ymin"],
                    row["xmax"], row["ymax"],
                    w, h
                )

                f.write(f"0 {x} {y} {bw} {bh}\n")

In [9]:
create_labels(train_imgs, "train")
create_labels(val_imgs, "val")

Создаем yaml файл, где указываем пути до train и val выборки, а так же указыавем имеющиеся у нас классы.

In [10]:
yaml_text = """
train: D:/python/II/dataset/images/train
val: D:/python/II/dataset/images/val

names:
  0: car
"""

with open("data.yaml", "w") as f:
    f.write(yaml_text)

Проверяем выборку на битые файлы

In [11]:
labels_path = "dataset/labels/train"

empty_files = []

for f in os.listdir(labels_path):
    path = os.path.join(labels_path, f)
    if os.path.getsize(path) == 0:
        empty_files.append(f)

print("Empty label files:", len(empty_files))
print(empty_files[:10])

Empty label files: 0
[]

In [12]:
from PIL import Image

bad = []

for root, _, files in os.walk("dataset/images"):
    for f in files:
        try:
            Image.open(os.path.join(root, f)).verify()
        except:
            bad.append(f)

print("Bad images:", bad)

Bad images: []

Запускаем обучение. Я тестировал разное количество эпох и в целом количество эпох больше 25+- не дает никакой прибавки. Но для финальной версии я решил оставить 40

In [13]:
from ultralytics import YOLO

model = YOLO("yolo11n.pt")

model.train(
    data="data.yaml",
    epochs=40,
    imgsz=640,
    batch=4,
    workers=0,
    name="yolo11n_exp",
    exist_ok=True
)

New https://pypi.org/project/ultralytics/8.4.41 available  Update with 'pip install -U ultralytics'
Ultralytics 8.3.0  Python-3.12.9 torch-2.3.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
engine\trainer: task=detect, mode=train, model=yolo11n.pt, data=data.yaml, epochs=40, time=None, patience=100, batch=4, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=0, project=None, name=yolo11n_exp, exist_ok=True, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=True, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, copy_paste_mode=flip, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs\detect\yolo11n_exp
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    111296  ultralytics.nn.modules.block.C3k2            [384, 128, 1, False]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1     32096  ultralytics.nn.modules.block.C3k2            [256, 64, 1, False]
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1     86720  ultralytics.nn.modules.block.C3k2            [192, 128, 1, False]
 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1    378880  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True]
 23        [16, 19, 22]  1    430867  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
YOLO11n summary: 319 layers, 2,590,035 parameters, 2,590,019 gradients, 6.4 GFLOPs

Transferred 448/499 items from pretrained weights
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed

train: Scanning D:\python\II\dataset\labels\train... 284 images, 0 backgrounds, 0 corrupt: 100%|██████████| 284/284

train: New cache created: D:\python\II\dataset\labels\train.cache

val: Scanning D:\python\II\dataset\labels\val... 71 images, 0 backgrounds, 0 corrupt: 100%|██████████| 71/71 [00:00

val: New cache created: D:\python\II\dataset\labels\val.cache

Plotting labels to runs\detect\yolo11n_exp\labels.jpg...
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.002, momentum=0.9) with parameter groups 81 weight(decay=0.0), 88 weight(decay=0.0005), 87 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 0 dataloader workers
Logging results to runs\detect\yolo11n_exp
Starting training for 40 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       1/40      0.73G      1.417      2.312      1.156         14        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.915      0.227      0.837      0.451

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       2/40     0.711G      1.401      1.722      1.227         10        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.917       0.83      0.902      0.528

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       3/40     0.711G      1.415      1.505      1.214          9        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.956      0.904      0.936      0.561

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       4/40     0.711G      1.357      1.338      1.199         20        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.914      0.889      0.911      0.537

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       5/40     0.719G       1.33      1.276      1.184         10        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.973      0.908      0.958      0.586

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       6/40     0.711G      1.315      1.262      1.167         18        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.945      0.908      0.962      0.625

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       7/40     0.711G      1.287      1.084      1.161         10        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.952      0.899      0.972      0.572

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       8/40     0.711G      1.247      1.037      1.155         18        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.982      0.922      0.962      0.599

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       9/40     0.711G      1.261      1.018      1.155          9        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.982      0.927      0.967      0.632

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      10/40     0.711G      1.239      0.973      1.131         11        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.982      0.914       0.97      0.609

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      11/40     0.711G      1.262     0.9296      1.127         16        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.955      0.933      0.976      0.552

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      12/40     0.711G      1.233     0.8634      1.116          9        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.987       0.95      0.976      0.614

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      13/40     0.711G      1.235     0.8425       1.12         10        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119       0.99      0.941      0.971      0.624

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      14/40     0.711G      1.185     0.8454      1.089         10        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.991      0.949       0.97      0.624

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      15/40     0.711G      1.181     0.7898      1.103         17        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.979      0.933      0.976      0.607

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      16/40     0.711G      1.156     0.7764      1.089          9        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.981      0.941      0.969      0.619

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      17/40     0.711G      1.133     0.7479      1.069          4        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.991      0.947       0.97      0.615

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      18/40     0.711G      1.156     0.7541      1.079         24        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.989      0.958      0.978      0.598

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      19/40     0.711G      1.194     0.7354      1.105         13        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.983      0.957      0.983      0.626

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      20/40     0.711G       1.14     0.7129      1.074         10        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.997      0.933       0.98      0.626

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      21/40     0.709G      1.109     0.6738      1.076         15        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.994      0.941      0.985       0.63

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      22/40     0.709G      1.122     0.6612      1.072         15        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119          1      0.941      0.978      0.628

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      23/40     0.709G      1.101     0.6622      1.076          5        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.974      0.947      0.975      0.611

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      24/40     0.709G      1.108     0.6518      1.059         19        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.963      0.958      0.973      0.647

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      25/40     0.711G      1.149     0.6511      1.068         11        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.974      0.958      0.973      0.645

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      26/40     0.709G      1.105     0.6501       1.06         10        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.997      0.933      0.979      0.641

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      27/40     0.709G       1.12      0.642      1.061         10        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.994       0.95      0.976      0.653

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      28/40     0.711G      1.118     0.6149      1.062          8        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.993      0.941      0.971      0.649

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      29/40     0.709G       1.09      0.622       1.04          8        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119          1      0.948      0.972      0.633

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      30/40     0.709G      1.088      0.604      1.035         12        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.984       0.95      0.974      0.654

Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      31/40     0.709G      1.088     0.6299      1.056          5        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.989      0.958      0.973      0.636

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      32/40     0.709G      1.036     0.6169      1.032          4        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.997       0.95      0.971      0.617

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      33/40     0.709G      1.032      0.599      1.035          4        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.991      0.951      0.974      0.624

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      34/40     0.709G      1.053     0.6104      1.019          8        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.982      0.958      0.977      0.636

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      35/40     0.709G      1.016     0.5905      1.017          7        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.982      0.943      0.975      0.647

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      36/40     0.709G       1.01     0.5867      1.028          4        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.991      0.939      0.969      0.645

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      37/40     0.715G      1.002     0.5807      1.037          2        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.972       0.95      0.976      0.649

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      38/40     0.709G     0.9985     0.5667       1.03          5        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119       0.99      0.941      0.978      0.649

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      39/40     0.709G     0.9934     0.5416      1.003          5        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.989      0.941      0.978      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      40/40     0.709G     0.9837     0.5417      1.009          4        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.988      0.941      0.977       0.65

40 epochs completed in 0.126 hours.
Optimizer stripped from runs\detect\yolo11n_exp\weights\last.pt, 5.4MB
Optimizer stripped from runs\detect\yolo11n_exp\weights\best.pt, 5.4MB

Validating runs\detect\yolo11n_exp\weights\best.pt...
Ultralytics 8.3.0  Python-3.12.9 torch-2.3.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
YOLO11n summary (fused): 238 layers, 2,582,347 parameters, 0 gradients, 6.3 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.984       0.95      0.974      0.654
Speed: 0.3ms preprocess, 3.7ms inference, 0.0ms loss, 1.2ms postprocess per image
Results saved to runs\detect\yolo11n_exp

ultralytics.utils.metrics.DetMetrics object with attributes:

ap_class_index: array([0])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x00000290B10D71A0>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,
           0.43243,     0.43343,     0.43443,     0.43544,     0.43644,     0.43744,     0.43844,     0.43944,     0.44044,     0.44144,     0.44244,     0.44344,     0.44444,     0.44545,     0.44645,     0.44745,     0.44845,     0.44945,     0.45045,     0.45145,     0.45245,     0.45345,     0.45445,     0.45546,
           0.45646,     0.45746,     0.45846,     0.45946,     0.46046,     0.46146,     0.46246,     0.46346,     0.46446,     0.46547,     0.46647,     0.46747,     0.46847,     0.46947,     0.47047,     0.47147,     0.47247,     0.47347,     0.47447,     0.47548,     0.47648,     0.47748,     0.47848,     0.47948,
           0.48048,     0.48148,     0.48248,     0.48348,     0.48448,     0.48549,     0.48649,     0.48749,     0.48849,     0.48949,     0.49049,     0.49149,     0.49249,     0.49349,     0.49449,      0.4955,      0.4965,      0.4975,      0.4985,      0.4995,      0.5005,      0.5015,      0.5025,      0.5035,
            0.5045,     0.50551,     0.50651,     0.50751,     0.50851,     0.50951,     0.51051,     0.51151,     0.51251,     0.51351,     0.51451,     0.51552,     0.51652,     0.51752,     0.51852,     0.51952,     0.52052,     0.52152,     0.52252,     0.52352,     0.52452,     0.52553,     0.52653,     0.52753,
           0.52853,     0.52953,     0.53053,     0.53153,     0.53253,     0.53353,     0.53453,     0.53554,     0.53654,     0.53754,     0.53854,     0.53954,     0.54054,     0.54154,     0.54254,     0.54354,     0.54454,     0.54555,     0.54655,     0.54755,     0.54855,     0.54955,     0.55055,     0.55155,
           0.55255,     0.55355,     0.55455,     0.55556,     0.55656,     0.55756,     0.55856,     0.55956,     0.56056,     0.56156,     0.56256,     0.56356,     0.56456,     0.56557,     0.56657,     0.56757,     0.56857,     0.56957,     0.57057,     0.57157,     0.57257,     0.57357,     0.57457,     0.57558,
           0.57658,     0.57758,     0.57858,     0.57958,     0.58058,     0.58158,     0.58258,     0.58358,     0.58458,     0.58559,     0.58659,     0.58759,     0.58859,     0.58959,     0.59059,     0.59159,     0.59259,     0.59359,     0.59459,      0.5956,      0.5966,      0.5976,      0.5986,      0.5996,
            0.6006,      0.6016,      0.6026,      0.6036,      0.6046,     0.60561,     0.60661,     0.60761,     0.60861,     0.60961,     0.61061,     0.61161,     0.61261,     0.61361,     0.61461,     0.61562,     0.61662,     0.61762,     0.61862,     0.61962,     0.62062,     0.62162,     0.62262,     0.62362,
           0.62462,     0.62563,     0.62663,     0.62763,     0.62863,     0.62963,     0.63063,     0.63163,     0.63263,     0.63363,     0.63463,     0.63564,     0.63664,     0.63764,     0.63864,     0.63964,     0.64064,     0.64164,     0.64264,     0.64364,     0.64464,     0.64565,     0.64665,     0.64765,
           0.64865,     0.64965,     0.65065,     0.65165,     0.65265,     0.65365,     0.65465,     0.65566,     0.65666,     0.65766,     0.65866,     0.65966,     0.66066,     0.66166,     0.66266,     0.66366,     0.66466,     0.66567,     0.66667,     0.66767,     0.66867,     0.66967,     0.67067,     0.67167,
           0.67267,     0.67367,     0.67467,     0.67568,     0.67668,     0.67768,     0.67868,     0.67968,     0.68068,     0.68168,     0.68268,     0.68368,     0.68468,     0.68569,     0.68669,     0.68769,     0.68869,     0.68969,     0.69069,     0.69169,     0.69269,     0.69369,     0.69469,      0.6957,
            0.6967,      0.6977,      0.6987,      0.6997,      0.7007,      0.7017,      0.7027,      0.7037,      0.7047,     0.70571,     0.70671,     0.70771,     0.70871,     0.70971,     0.71071,     0.71171,     0.71271,     0.71371,     0.71471,     0.71572,     0.71672,     0.71772,     0.71872,     0.71972,
           0.72072,     0.72172,     0.72272,     0.72372,     0.72472,     0.72573,     0.72673,     0.72773,     0.72873,     0.72973,     0.73073,     0.73173,     0.73273,     0.73373,     0.73473,     0.73574,     0.73674,     0.73774,     0.73874,     0.73974,     0.74074,     0.74174,     0.74274,     0.74374,
           0.74474,     0.74575,     0.74675,     0.74775,     0.74875,     0.74975,     0.75075,     0.75175,     0.75275,     0.75375,     0.75475,     0.75576,     0.75676,     0.75776,     0.75876,     0.75976,     0.76076,     0.76176,     0.76276,     0.76376,     0.76476,     0.76577,     0.76677,     0.76777,
           0.76877,     0.76977,     0.77077,     0.77177,     0.77277,     0.77377,     0.77477,     0.77578,     0.77678,     0.77778,     0.77878,     0.77978,     0.78078,     0.78178,     0.78278,     0.78378,     0.78478,     0.78579,     0.78679,     0.78779,     0.78879,     0.78979,     0.79079,     0.79179,
           0.79279,     0.79379,     0.79479,      0.7958,      0.7968,      0.7978,      0.7988,      0.7998,      0.8008,      0.8018,      0.8028,      0.8038,      0.8048,     0.80581,     0.80681,     0.80781,     0.80881,     0.80981,     0.81081,     0.81181,     0.81281,     0.81381,     0.81481,     0.81582,
           0.81682,     0.81782,     0.81882,     0.81982,     0.82082,     0.82182,     0.82282,     0.82382,     0.82482,     0.82583,     0.82683,     0.82783,     0.82883,     0.82983,     0.83083,     0.83183,     0.83283,     0.83383,     0.83483,     0.83584,     0.83684,     0.83784,     0.83884,     0.83984,
           0.84084,     0.84184,     0.84284,     0.84384,     0.84484,     0.84585,     0.84685,     0.84785,     0.84885,     0.84985,     0.85085,     0.85185,     0.85285,     0.85385,     0.85485,     0.85586,     0.85686,     0.85786,     0.85886,     0.85986,     0.86086,     0.86186,     0.86286,     0.86386,
           0.86486,     0.86587,     0.86687,     0.86787,     0.86887,     0.86987,     0.87087,     0.87187,     0.87287,     0.87387,     0.87487,     0.87588,     0.87688,     0.87788,     0.87888,     0.87988,     0.88088,     0.88188,     0.88288,     0.88388,     0.88488,     0.88589,     0.88689,     0.88789,
           0.88889,     0.88989,     0.89089,     0.89189,     0.89289,     0.89389,     0.89489,      0.8959,      0.8969,      0.8979,      0.8989,      0.8999,      0.9009,      0.9019,      0.9029,      0.9039,      0.9049,     0.90591,     0.90691,     0.90791,     0.90891,     0.90991,     0.91091,     0.91191,
           0.91291,     0.91391,     0.91491,     0.91592,     0.91692,     0.91792,     0.91892,     0.91992,     0.92092,     0.92192,     0.92292,     0.92392,     0.92492,     0.92593,     0.92693,     0.92793,     0.92893,     0.92993,     0.93093,     0.93193,     0.93293,     0.93393,     0.93493,     0.93594,
           0.93694,     0.93794,     0.93894,     0.93994,     0.94094,     0.94194,     0.94294,     0.94394,     0.94494,     0.94595,     0.94695,     0.94795,     0.94895,     0.94995,     0.95095,     0.95195,     0.95295,     0.95395,     0.95495,     0.95596,     0.95696,     0.95796,     0.95896,     0.95996,
           0.96096,     0.96196,     0.96296,     0.96396,     0.96496,     0.96597,     0.96697,     0.96797,     0.96897,     0.96997,     0.97097,     0.97197,     0.97297,     0.97397,     0.97497,     0.97598,     0.97698,     0.97798,     0.97898,     0.97998,     0.98098,     0.98198,     0.98298,     0.98398,
           0.98498,     0.98599,     0.98699,     0.98799,     0.98899,     0.98999,     0.99099,     0.99199,     0.99299,     0.99399,     0.99499,       0.996,       0.997,       0.998,       0.999,           1]), array([[          1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,

Смотрим лучшише метрики:

In [14]:
model = YOLO("runs/detect/yolo11n_exp/weights/best.pt") 

metrics = model.val(data="data.yaml")

results = []

print("\n===== YOLO11n =====")
print(f"Precision: {metrics.box.mp:.4f}")
print(f"Recall:    {metrics.box.mr:.4f}")
print(f"mAP50:     {metrics.box.map50:.4f}")
print(f"mAP50-95:  {metrics.box.map:.4f}")

results.append({
    "Model": "YOLO11n",
    "Precision": metrics.box.mp,
    "Recall": metrics.box.mr,
    "mAP50": metrics.box.map50,
    "mAP50-95": metrics.box.map
})

Ultralytics 8.3.0  Python-3.12.9 torch-2.3.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
YOLO11n summary (fused): 238 layers, 2,582,347 parameters, 0 gradients, 6.3 GFLOPs

val: Scanning D:\python\II\dataset\labels\val.cache... 71 images, 0 backgrounds, 0 corrupt: 100%|██████████| 71/71
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 5/5 [00:

                   all         71        119      0.984       0.95      0.974      0.654
Speed: 1.1ms preprocess, 8.5ms inference, 0.0ms loss, 2.9ms postprocess per image
Results saved to runs\detect\val

===== YOLO11n =====
Precision: 0.9841
Recall:    0.9496
mAP50:     0.9737
mAP50-95:  0.6545

Высокое значение Precision указывает на то, что модель практически не допускает ложноположительных срабатываний, то есть обнаруженные объекты в большинстве случаев действительно являются автомобилями.

Значение Recall также находится на высоком уровне, что говорит о способности модели находить большинство объектов на изображении. Тем не менее, небольшая разница между Precision и Recall свидетельствует о том, что часть объектов всё же пропускается.

Метрика mAP50 показывает, что при пороге IoU = 0.5 модель демонстрирует очень высокое качество детекции, корректно определяя объекты и их границы в большинстве случаев.

Однако более строгая метрика mAP50-95 значительно ниже. Это связано с тем, что она учитывает качество локализации при разных порогах IoU (от 0.5 до 0.95). Такое снижение указывает на то, что модель не всегда точно определяет границы объектов, особенно при более строгих требованиях к совпадению.

Анализируя метрики, мы можем сделать вывод, что единственное, что нам нужно - пытаться повысить mAP50-95. Остальные метрики уже показывают хорошие результаты. Вот мои гипотезы:

1. Гипотеза: использование более сложной архитектуры модели (YOLO11s вместо YOLO11n) приведёт к увеличению качества локализации объектов за счёт более выразительного представления признаков, что в первую очередь повысит метрику mAP50-95, так как она наиболее чувствительна к точности bounding box при строгих IoU-порогах.

2. Гипотеза: применение усиленных аугментаций данных (mosaic, mixup, цветовые и геометрические преобразования) повысит устойчивость модели к вариативности изображений и улучшит качество обобщения, что приведёт к росту метрики mAP50-95 за счёт более стабильного определения границ объектов в различных условиях.

3. Гипотеза: изменение стратегии дообучения модели через заморозку части слоёв (backbone freezing) на начальных этапах обучения позволит улучшить качество извлечения признаков и стабилизировать обучение, что приведёт к повышению метрики mAP50-95 за счёт более устойчивой адаптации модели к домену данных.

# Для начала проверим гипотезу 1:

In [15]:
model.train(
    data="data.yaml",
    epochs=40,
    imgsz=640,
    batch=4,
    workers=0,
    name="yolo11s_exp",
    exist_ok=True
)

New https://pypi.org/project/ultralytics/8.4.41 available  Update with 'pip install -U ultralytics'
Ultralytics 8.3.0  Python-3.12.9 torch-2.3.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
engine\trainer: task=detect, mode=train, model=runs/detect/yolo11n_exp/weights/best.pt, data=data.yaml, epochs=40, time=None, patience=100, batch=4, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=0, project=None, name=yolo11s_exp, exist_ok=True, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=True, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, copy_paste_mode=flip, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs\detect\yolo11s_exp

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    111296  ultralytics.nn.modules.block.C3k2            [384, 128, 1, False]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1     32096  ultralytics.nn.modules.block.C3k2            [256, 64, 1, False]
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1     86720  ultralytics.nn.modules.block.C3k2            [192, 128, 1, False]
 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1    378880  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True]
 23        [16, 19, 22]  1    430867  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
YOLO11n summary: 319 layers, 2,590,035 parameters, 2,590,019 gradients, 6.4 GFLOPs

Transferred 94/499 items from pretrained weights
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed

train: Scanning D:\python\II\dataset\labels\train.cache... 284 images, 0 backgrounds, 0 corrupt: 100%|██████████| 2
val: Scanning D:\python\II\dataset\labels\val.cache... 71 images, 0 backgrounds, 0 corrupt: 100%|██████████| 71/71

Plotting labels to runs\detect\yolo11s_exp\labels.jpg...

optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.002, momentum=0.9) with parameter groups 81 weight(decay=0.0), 88 weight(decay=0.0005), 87 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 0 dataloader workers
Logging results to runs\detect\yolo11s_exp
Starting training for 40 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       1/40      0.69G      1.531      1.153      1.307         14        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.927      0.858      0.931      0.555

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       2/40     0.694G      1.268     0.9001      1.126         10        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.957      0.932      0.959      0.564

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       3/40     0.728G      1.247     0.8357      1.095          9        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.973      0.922      0.967      0.605

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       4/40     0.728G       1.21     0.7917       1.09         20        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.965      0.921      0.952      0.591

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       5/40     0.736G      1.181     0.7536      1.066         10        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.987      0.924      0.971      0.578

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       6/40     0.728G      1.216     0.7309      1.089         18        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.987      0.899      0.957      0.586

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       7/40     0.728G      1.191     0.6934      1.076         10        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.973      0.909      0.969      0.625

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       8/40     0.728G      1.161     0.6737      1.065         18        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119       0.98      0.924      0.974      0.617

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       9/40     0.728G      1.104     0.6332      1.059          9        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.927      0.959      0.969      0.631

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      10/40     0.728G      1.115     0.6472      1.054         11        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.974      0.958      0.967      0.627

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      11/40     0.728G      1.118     0.6208      1.048         16        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.989      0.941      0.973      0.623

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      12/40     0.728G      1.116     0.6097      1.055          9        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.991      0.948      0.975      0.621

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      13/40     0.728G      1.118     0.6067      1.052         10        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119       0.98      0.966      0.976      0.627

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      14/40     0.728G      1.088     0.5917      1.042         10        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.975      0.966      0.976      0.657

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      15/40     0.728G      1.104     0.5849      1.052         17        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.967      0.972      0.977      0.652

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      16/40     0.728G      1.089     0.5795      1.033          9        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.975      0.972      0.977      0.635

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      17/40     0.728G      1.064     0.5625      1.024          4        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.975      0.964      0.977      0.652

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      18/40     0.728G      1.048     0.5593       1.02         24        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.983      0.966      0.976      0.654

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      19/40     0.728G      1.095     0.5697      1.036         13        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.991      0.958      0.976      0.644

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      20/40     0.728G      1.044     0.5638      1.022         10        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.956      0.966      0.976      0.665

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      21/40     0.736G      1.036     0.5451      1.025         15        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.985       0.95      0.978      0.666

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      22/40     0.728G      1.031     0.5394      1.027         15        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.974      0.966      0.977      0.672

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      23/40     0.728G      1.022     0.5525      1.029          5        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.983      0.959      0.978       0.64

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      24/40     0.728G      1.029     0.5418      1.022         19        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119       0.98       0.95      0.976       0.67

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      25/40     0.728G      1.034     0.5298      1.011         11        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.982      0.938      0.975      0.671

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      26/40     0.728G      1.028     0.5271      1.013         10        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.982      0.939      0.976       0.67

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      27/40     0.728G      1.041     0.5263      1.023         10        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119       0.95       0.96      0.976      0.667

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      28/40     0.728G       1.06     0.5268      1.029          8        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.978      0.933      0.975      0.655

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      29/40     0.728G      1.031     0.5242      1.016          8        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.981      0.933      0.976      0.668

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      30/40     0.728G      1.031     0.5169      1.009         12        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.982      0.938      0.975      0.667

Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      31/40     0.728G      1.041      0.517      1.033          5        640: 100%|██████████| 71/71 [00:08<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.991       0.94      0.974      0.659

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      32/40     0.728G     0.9961     0.5035      1.006          4        640: 100%|██████████| 71/71 [00:08<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.974      0.939      0.975      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      33/40     0.728G      1.003     0.4866      1.023          4        640: 100%|██████████| 71/71 [00:08<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.977      0.941      0.976      0.667

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      34/40     0.728G      1.003     0.4875     0.9997          8        640: 100%|██████████| 71/71 [00:08<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.966      0.958      0.976       0.67

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      35/40     0.728G      1.006     0.4939      1.014          7        640: 100%|██████████| 71/71 [00:08<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.963      0.958      0.977      0.675

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      36/40     0.728G     0.9867     0.4916      1.017          4        640: 100%|██████████| 71/71 [00:08<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.959      0.958      0.977      0.671

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      37/40     0.734G     0.9796     0.4866      1.021          2        640: 100%|██████████| 71/71 [00:08<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.952      0.966      0.977      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      38/40     0.728G     0.9758     0.4928      1.019          5        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.955      0.966      0.977      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      39/40     0.728G     0.9789     0.4796     0.9998          5        640: 100%|██████████| 71/71 [00:08<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.958      0.964      0.977      0.679

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      40/40     0.728G     0.9605      0.471      1.002          4        640: 100%|██████████| 71/71 [00:08<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.958      0.965      0.977       0.68

40 epochs completed in 0.120 hours.
Optimizer stripped from runs\detect\yolo11s_exp\weights\last.pt, 5.4MB
Optimizer stripped from runs\detect\yolo11s_exp\weights\best.pt, 5.4MB

Validating runs\detect\yolo11s_exp\weights\best.pt...
Ultralytics 8.3.0  Python-3.12.9 torch-2.3.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
YOLO11n summary (fused): 238 layers, 2,582,347 parameters, 0 gradients, 6.3 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.958      0.965      0.977      0.681
Speed: 0.3ms preprocess, 2.9ms inference, 0.0ms loss, 0.9ms postprocess per image
Results saved to runs\detect\yolo11s_exp

ultralytics.utils.metrics.DetMetrics object with attributes:

ap_class_index: array([0])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x0000029094C6F980>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,
           0.43243,     0.43343,     0.43443,     0.43544,     0.43644,     0.43744,     0.43844,     0.43944,     0.44044,     0.44144,     0.44244,     0.44344,     0.44444,     0.44545,     0.44645,     0.44745,     0.44845,     0.44945,     0.45045,     0.45145,     0.45245,     0.45345,     0.45445,     0.45546,
           0.45646,     0.45746,     0.45846,     0.45946,     0.46046,     0.46146,     0.46246,     0.46346,     0.46446,     0.46547,     0.46647,     0.46747,     0.46847,     0.46947,     0.47047,     0.47147,     0.47247,     0.47347,     0.47447,     0.47548,     0.47648,     0.47748,     0.47848,     0.47948,
           0.48048,     0.48148,     0.48248,     0.48348,     0.48448,     0.48549,     0.48649,     0.48749,     0.48849,     0.48949,     0.49049,     0.49149,     0.49249,     0.49349,     0.49449,      0.4955,      0.4965,      0.4975,      0.4985,      0.4995,      0.5005,      0.5015,      0.5025,      0.5035,
            0.5045,     0.50551,     0.50651,     0.50751,     0.50851,     0.50951,     0.51051,     0.51151,     0.51251,     0.51351,     0.51451,     0.51552,     0.51652,     0.51752,     0.51852,     0.51952,     0.52052,     0.52152,     0.52252,     0.52352,     0.52452,     0.52553,     0.52653,     0.52753,
           0.52853,     0.52953,     0.53053,     0.53153,     0.53253,     0.53353,     0.53453,     0.53554,     0.53654,     0.53754,     0.53854,     0.53954,     0.54054,     0.54154,     0.54254,     0.54354,     0.54454,     0.54555,     0.54655,     0.54755,     0.54855,     0.54955,     0.55055,     0.55155,
           0.55255,     0.55355,     0.55455,     0.55556,     0.55656,     0.55756,     0.55856,     0.55956,     0.56056,     0.56156,     0.56256,     0.56356,     0.56456,     0.56557,     0.56657,     0.56757,     0.56857,     0.56957,     0.57057,     0.57157,     0.57257,     0.57357,     0.57457,     0.57558,
           0.57658,     0.57758,     0.57858,     0.57958,     0.58058,     0.58158,     0.58258,     0.58358,     0.58458,     0.58559,     0.58659,     0.58759,     0.58859,     0.58959,     0.59059,     0.59159,     0.59259,     0.59359,     0.59459,      0.5956,      0.5966,      0.5976,      0.5986,      0.5996,
            0.6006,      0.6016,      0.6026,      0.6036,      0.6046,     0.60561,     0.60661,     0.60761,     0.60861,     0.60961,     0.61061,     0.61161,     0.61261,     0.61361,     0.61461,     0.61562,     0.61662,     0.61762,     0.61862,     0.61962,     0.62062,     0.62162,     0.62262,     0.62362,
           0.62462,     0.62563,     0.62663,     0.62763,     0.62863,     0.62963,     0.63063,     0.63163,     0.63263,     0.63363,     0.63463,     0.63564,     0.63664,     0.63764,     0.63864,     0.63964,     0.64064,     0.64164,     0.64264,     0.64364,     0.64464,     0.64565,     0.64665,     0.64765,
           0.64865,     0.64965,     0.65065,     0.65165,     0.65265,     0.65365,     0.65465,     0.65566,     0.65666,     0.65766,     0.65866,     0.65966,     0.66066,     0.66166,     0.66266,     0.66366,     0.66466,     0.66567,     0.66667,     0.66767,     0.66867,     0.66967,     0.67067,     0.67167,
           0.67267,     0.67367,     0.67467,     0.67568,     0.67668,     0.67768,     0.67868,     0.67968,     0.68068,     0.68168,     0.68268,     0.68368,     0.68468,     0.68569,     0.68669,     0.68769,     0.68869,     0.68969,     0.69069,     0.69169,     0.69269,     0.69369,     0.69469,      0.6957,
            0.6967,      0.6977,      0.6987,      0.6997,      0.7007,      0.7017,      0.7027,      0.7037,      0.7047,     0.70571,     0.70671,     0.70771,     0.70871,     0.70971,     0.71071,     0.71171,     0.71271,     0.71371,     0.71471,     0.71572,     0.71672,     0.71772,     0.71872,     0.71972,
           0.72072,     0.72172,     0.72272,     0.72372,     0.72472,     0.72573,     0.72673,     0.72773,     0.72873,     0.72973,     0.73073,     0.73173,     0.73273,     0.73373,     0.73473,     0.73574,     0.73674,     0.73774,     0.73874,     0.73974,     0.74074,     0.74174,     0.74274,     0.74374,
           0.74474,     0.74575,     0.74675,     0.74775,     0.74875,     0.74975,     0.75075,     0.75175,     0.75275,     0.75375,     0.75475,     0.75576,     0.75676,     0.75776,     0.75876,     0.75976,     0.76076,     0.76176,     0.76276,     0.76376,     0.76476,     0.76577,     0.76677,     0.76777,
           0.76877,     0.76977,     0.77077,     0.77177,     0.77277,     0.77377,     0.77477,     0.77578,     0.77678,     0.77778,     0.77878,     0.77978,     0.78078,     0.78178,     0.78278,     0.78378,     0.78478,     0.78579,     0.78679,     0.78779,     0.78879,     0.78979,     0.79079,     0.79179,
           0.79279,     0.79379,     0.79479,      0.7958,      0.7968,      0.7978,      0.7988,      0.7998,      0.8008,      0.8018,      0.8028,      0.8038,      0.8048,     0.80581,     0.80681,     0.80781,     0.80881,     0.80981,     0.81081,     0.81181,     0.81281,     0.81381,     0.81481,     0.81582,
           0.81682,     0.81782,     0.81882,     0.81982,     0.82082,     0.82182,     0.82282,     0.82382,     0.82482,     0.82583,     0.82683,     0.82783,     0.82883,     0.82983,     0.83083,     0.83183,     0.83283,     0.83383,     0.83483,     0.83584,     0.83684,     0.83784,     0.83884,     0.83984,
           0.84084,     0.84184,     0.84284,     0.84384,     0.84484,     0.84585,     0.84685,     0.84785,     0.84885,     0.84985,     0.85085,     0.85185,     0.85285,     0.85385,     0.85485,     0.85586,     0.85686,     0.85786,     0.85886,     0.85986,     0.86086,     0.86186,     0.86286,     0.86386,
           0.86486,     0.86587,     0.86687,     0.86787,     0.86887,     0.86987,     0.87087,     0.87187,     0.87287,     0.87387,     0.87487,     0.87588,     0.87688,     0.87788,     0.87888,     0.87988,     0.88088,     0.88188,     0.88288,     0.88388,     0.88488,     0.88589,     0.88689,     0.88789,
           0.88889,     0.88989,     0.89089,     0.89189,     0.89289,     0.89389,     0.89489,      0.8959,      0.8969,      0.8979,      0.8989,      0.8999,      0.9009,      0.9019,      0.9029,      0.9039,      0.9049,     0.90591,     0.90691,     0.90791,     0.90891,     0.90991,     0.91091,     0.91191,
           0.91291,     0.91391,     0.91491,     0.91592,     0.91692,     0.91792,     0.91892,     0.91992,     0.92092,     0.92192,     0.92292,     0.92392,     0.92492,     0.92593,     0.92693,     0.92793,     0.92893,     0.92993,     0.93093,     0.93193,     0.93293,     0.93393,     0.93493,     0.93594,
           0.93694,     0.93794,     0.93894,     0.93994,     0.94094,     0.94194,     0.94294,     0.94394,     0.94494,     0.94595,     0.94695,     0.94795,     0.94895,     0.94995,     0.95095,     0.95195,     0.95295,     0.95395,     0.95495,     0.95596,     0.95696,     0.95796,     0.95896,     0.95996,
           0.96096,     0.96196,     0.96296,     0.96396,     0.96496,     0.96597,     0.96697,     0.96797,     0.96897,     0.96997,     0.97097,     0.97197,     0.97297,     0.97397,     0.97497,     0.97598,     0.97698,     0.97798,     0.97898,     0.97998,     0.98098,     0.98198,     0.98298,     0.98398,
           0.98498,     0.98599,     0.98699,     0.98799,     0.98899,     0.98999,     0.99099,     0.99199,     0.99299,     0.99399,     0.99499,       0.996,       0.997,       0.998,       0.999,           1]), array([[          1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,

In [16]:
from ultralytics import YOLO

model = YOLO("runs/detect/yolo11s_exp/weights/best.pt")  

metrics = model.val(data="data.yaml")

print("\n===== YOLO11s =====")
print(f"Precision: {metrics.box.mp:.4f}")
print(f"Recall:    {metrics.box.mr:.4f}")
print(f"mAP50:     {metrics.box.map50:.4f}")
print(f"mAP50-95:  {metrics.box.map:.4f}")

results.append({
    "Model": "YOLO11s",
    "Precision": metrics.box.mp,
    "Recall": metrics.box.mr,
    "mAP50": metrics.box.map50,
    "mAP50-95": metrics.box.map
})

Ultralytics 8.3.0  Python-3.12.9 torch-2.3.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
YOLO11n summary (fused): 238 layers, 2,582,347 parameters, 0 gradients, 6.3 GFLOPs

val: Scanning D:\python\II\dataset\labels\val.cache... 71 images, 0 backgrounds, 0 corrupt: 100%|██████████| 71/71
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 5/5 [00:

                   all         71        119      0.958      0.965      0.977      0.679
Speed: 1.2ms preprocess, 6.1ms inference, 0.0ms loss, 2.0ms postprocess per image
Results saved to runs\detect\val2

===== YOLO11s =====
Precision: 0.9583
Recall:    0.9654
mAP50:     0.9768
mAP50-95:  0.6793

Как можно заметить по новым метрикам практически ничего не изменилось. Модель стала делать чуть больше ложных срабатываний, при этом она стала находить чуть больше объектов на изображении. Ну и наш показатель mAP50-95 тоже чуть вырос, но слишком незначительно, чтобы это можно было считать хоть в какой-нибудь степени успехом. Теперь проверим другие гипотезы. Будем их использовать уже сразу с улучшенной моделью.

# Проверяем гипотезу 2:

In [17]:
model_aug = YOLO("yolo11s.pt")

model_aug.train(
    data="data.yaml",
    epochs=40,
    imgsz=640,
    batch=4,
    workers=0,
    name="yolo11s_aug_exp",
    exist_ok=True,
    mosaic=1.0,
    mixup=0.2,
    hsv_h=0.015,
    hsv_s=0.7,
    hsv_v=0.4,
    fliplr=0.5
)

New https://pypi.org/project/ultralytics/8.4.41 available  Update with 'pip install -U ultralytics'
Ultralytics 8.3.0  Python-3.12.9 torch-2.3.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
engine\trainer: task=detect, mode=train, model=yolo11s.pt, data=data.yaml, epochs=40, time=None, patience=100, batch=4, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=0, project=None, name=yolo11s_aug_exp, exist_ok=True, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=True, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.2, copy_paste=0.0, copy_paste_mode=flip, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs\detect\yolo11s_aug_exp
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  3                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  4                  -1  1    103360  ultralytics.nn.modules.block.C3k2            [128, 256, 1, False, 0.25]
  5                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
  6                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1    990976  ultralytics.nn.modules.block.C2PSA           [512, 512, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    443776  ultralytics.nn.modules.block.C3k2            [768, 256, 1, False]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1    127680  ultralytics.nn.modules.block.C3k2            [512, 128, 1, False]
 17                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1    345472  ultralytics.nn.modules.block.C3k2            [384, 256, 1, False]
 20                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1   1511424  ultralytics.nn.modules.block.C3k2            [768, 512, 1, True]
 23        [16, 19, 22]  1    819795  ultralytics.nn.modules.head.Detect           [1, [128, 256, 512]]
YOLO11s summary: 319 layers, 9,428,179 parameters, 9,428,163 gradients, 21.5 GFLOPs

Transferred 493/499 items from pretrained weights
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed

train: Scanning D:\python\II\dataset\labels\train.cache... 284 images, 0 backgrounds, 0 corrupt: 100%|██████████| 2
val: Scanning D:\python\II\dataset\labels\val.cache... 71 images, 0 backgrounds, 0 corrupt: 100%|██████████| 71/71

Plotting labels to runs\detect\yolo11s_aug_exp\labels.jpg...

optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.002, momentum=0.9) with parameter groups 81 weight(decay=0.0), 88 weight(decay=0.0005), 87 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 0 dataloader workers
Logging results to runs\detect\yolo11s_aug_exp
Starting training for 40 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       1/40       1.3G      1.526      2.647      1.245          7        640: 100%|██████████| 71/71 [00:13<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.931      0.924      0.954      0.572

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       2/40      1.37G      1.447      1.146      1.225          7        640: 100%|██████████| 71/71 [00:12<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119        0.6      0.714      0.661      0.393

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       3/40      1.37G      1.451      1.077      1.217         17        640: 100%|██████████| 71/71 [00:12<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.827      0.887      0.902      0.527

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       4/40      1.37G      1.436      1.051      1.238         11        640: 100%|██████████| 71/71 [00:12<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119       0.86      0.908      0.913      0.516

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       5/40      1.39G      1.444      1.004      1.277         18        640: 100%|██████████| 71/71 [00:12<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.908      0.834      0.897      0.543

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       6/40      1.37G      1.372     0.8671      1.237         12        640: 100%|██████████| 71/71 [00:12<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.965      0.925      0.949       0.57

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       7/40      1.38G      1.335     0.8609      1.212         13        640: 100%|██████████| 71/71 [00:12<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.939      0.866      0.934      0.535

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       8/40      1.38G      1.309     0.7696      1.187          6        640: 100%|██████████| 71/71 [00:12<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.969      0.916      0.966      0.618

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       9/40      1.38G      1.326     0.7626      1.197         12        640: 100%|██████████| 71/71 [00:12<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.966      0.943      0.969       0.62

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      10/40      1.37G      1.313     0.7652      1.189         33        640: 100%|██████████| 71/71 [00:12<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.963      0.916      0.964      0.577

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      11/40      1.38G       1.29     0.7767      1.189         22        640: 100%|██████████| 71/71 [00:12<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.978      0.933      0.968      0.627

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      12/40      1.37G      1.287     0.7711      1.166          4        640: 100%|██████████| 71/71 [00:12<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.983      0.956      0.975      0.612

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      13/40      1.38G      1.229     0.6755      1.148         26        640: 100%|██████████| 71/71 [00:12<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.983      0.945      0.977       0.62

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      14/40      1.37G      1.241     0.6875      1.163         24        640: 100%|██████████| 71/71 [00:12<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.991      0.931      0.972       0.62

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      15/40      1.37G      1.215      0.681      1.135         13        640: 100%|██████████| 71/71 [00:12<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.942       0.95      0.977      0.599

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      16/40      1.37G       1.21     0.6516      1.128         27        640: 100%|██████████| 71/71 [00:12<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119       0.99       0.95      0.979      0.629

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      17/40      1.37G      1.255     0.6923      1.119         12        640: 100%|██████████| 71/71 [00:12<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.965      0.933      0.984      0.638

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      18/40      1.37G      1.224     0.6881      1.142          9        640: 100%|██████████| 71/71 [00:12<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.976       0.95      0.985      0.632

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      19/40      1.37G      1.152     0.6213      1.097         15        640: 100%|██████████| 71/71 [00:12<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.991      0.951       0.99      0.657

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      20/40      1.37G       1.18     0.6382      1.136         16        640: 100%|██████████| 71/71 [00:12<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.958      0.952       0.98      0.634

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      21/40      1.36G       1.18     0.6538       1.13         19        640: 100%|██████████| 71/71 [00:12<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.977      0.958      0.988      0.623

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      22/40      1.37G      1.164     0.5961      1.106         12        640: 100%|██████████| 71/71 [00:12<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.967       0.95      0.989      0.649

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      23/40      1.38G       1.15     0.5995      1.111         13        640: 100%|██████████| 71/71 [00:12<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.973      0.925      0.988      0.644

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      24/40      1.38G      1.166     0.6223      1.132         19        640: 100%|██████████| 71/71 [00:12<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.974      0.962      0.989      0.633

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      25/40      1.38G      1.177     0.5946      1.101         22        640: 100%|██████████| 71/71 [00:12<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.984      0.958      0.989      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      26/40      1.38G      1.198     0.5964      1.114          7        640: 100%|██████████| 71/71 [00:12<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.966      0.958      0.989      0.621

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      27/40      1.38G      1.137     0.5763       1.09         18        640: 100%|██████████| 71/71 [00:12<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.983      0.949      0.986      0.673

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      28/40      1.37G      1.145     0.5572      1.098         18        640: 100%|██████████| 71/71 [00:12<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.978      0.958      0.987      0.668

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      29/40      1.38G       1.15     0.5649      1.089         14        640: 100%|██████████| 71/71 [00:12<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.981       0.95      0.988      0.657

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      30/40      1.37G      1.115     0.5595      1.084          7        640: 100%|██████████| 71/71 [00:12<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.982      0.958      0.986      0.654

Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      31/40      1.39G      1.086     0.5209      1.096          5        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.982      0.958      0.981      0.651

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      32/40      1.38G      1.066     0.4888      1.079          3        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.974      0.956      0.975      0.632

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      33/40      1.37G       1.06     0.5047       1.09          4        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.972      0.958      0.976      0.652

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      34/40      1.39G      1.067     0.4834      1.076          7        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.953      0.983      0.984      0.632

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      35/40      1.37G      1.031     0.4882      1.077          8        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.966      0.969      0.984       0.66

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      36/40      1.38G      1.019     0.4735      1.037          5        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.981      0.966      0.988      0.664

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      37/40      1.39G      1.013     0.4794      1.046          3        640: 100%|██████████| 71/71 [00:11<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.966      0.964      0.987      0.674

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      38/40      1.37G     0.9961     0.4592      1.048          5        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.991      0.946      0.984      0.666

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      39/40      1.38G     0.9894     0.4559      1.052          5        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.973      0.958      0.987      0.646

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      40/40      1.38G     0.9807     0.4592      1.031          3        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.981      0.958      0.987      0.654

40 epochs completed in 0.151 hours.
Optimizer stripped from runs\detect\yolo11s_aug_exp\weights\last.pt, 19.2MB
Optimizer stripped from runs\detect\yolo11s_aug_exp\weights\best.pt, 19.2MB

Validating runs\detect\yolo11s_aug_exp\weights\best.pt...
Ultralytics 8.3.0  Python-3.12.9 torch-2.3.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
YOLO11s summary (fused): 238 layers, 9,413,187 parameters, 0 gradients, 21.3 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.966      0.964      0.987      0.674
Speed: 0.3ms preprocess, 5.5ms inference, 0.0ms loss, 0.9ms postprocess per image
Results saved to runs\detect\yolo11s_aug_exp

ultralytics.utils.metrics.DetMetrics object with attributes:

ap_class_index: array([0])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x00000290B09E4A10>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,
           0.43243,     0.43343,     0.43443,     0.43544,     0.43644,     0.43744,     0.43844,     0.43944,     0.44044,     0.44144,     0.44244,     0.44344,     0.44444,     0.44545,     0.44645,     0.44745,     0.44845,     0.44945,     0.45045,     0.45145,     0.45245,     0.45345,     0.45445,     0.45546,
           0.45646,     0.45746,     0.45846,     0.45946,     0.46046,     0.46146,     0.46246,     0.46346,     0.46446,     0.46547,     0.46647,     0.46747,     0.46847,     0.46947,     0.47047,     0.47147,     0.47247,     0.47347,     0.47447,     0.47548,     0.47648,     0.47748,     0.47848,     0.47948,
           0.48048,     0.48148,     0.48248,     0.48348,     0.48448,     0.48549,     0.48649,     0.48749,     0.48849,     0.48949,     0.49049,     0.49149,     0.49249,     0.49349,     0.49449,      0.4955,      0.4965,      0.4975,      0.4985,      0.4995,      0.5005,      0.5015,      0.5025,      0.5035,
            0.5045,     0.50551,     0.50651,     0.50751,     0.50851,     0.50951,     0.51051,     0.51151,     0.51251,     0.51351,     0.51451,     0.51552,     0.51652,     0.51752,     0.51852,     0.51952,     0.52052,     0.52152,     0.52252,     0.52352,     0.52452,     0.52553,     0.52653,     0.52753,
           0.52853,     0.52953,     0.53053,     0.53153,     0.53253,     0.53353,     0.53453,     0.53554,     0.53654,     0.53754,     0.53854,     0.53954,     0.54054,     0.54154,     0.54254,     0.54354,     0.54454,     0.54555,     0.54655,     0.54755,     0.54855,     0.54955,     0.55055,     0.55155,
           0.55255,     0.55355,     0.55455,     0.55556,     0.55656,     0.55756,     0.55856,     0.55956,     0.56056,     0.56156,     0.56256,     0.56356,     0.56456,     0.56557,     0.56657,     0.56757,     0.56857,     0.56957,     0.57057,     0.57157,     0.57257,     0.57357,     0.57457,     0.57558,
           0.57658,     0.57758,     0.57858,     0.57958,     0.58058,     0.58158,     0.58258,     0.58358,     0.58458,     0.58559,     0.58659,     0.58759,     0.58859,     0.58959,     0.59059,     0.59159,     0.59259,     0.59359,     0.59459,      0.5956,      0.5966,      0.5976,      0.5986,      0.5996,
            0.6006,      0.6016,      0.6026,      0.6036,      0.6046,     0.60561,     0.60661,     0.60761,     0.60861,     0.60961,     0.61061,     0.61161,     0.61261,     0.61361,     0.61461,     0.61562,     0.61662,     0.61762,     0.61862,     0.61962,     0.62062,     0.62162,     0.62262,     0.62362,
           0.62462,     0.62563,     0.62663,     0.62763,     0.62863,     0.62963,     0.63063,     0.63163,     0.63263,     0.63363,     0.63463,     0.63564,     0.63664,     0.63764,     0.63864,     0.63964,     0.64064,     0.64164,     0.64264,     0.64364,     0.64464,     0.64565,     0.64665,     0.64765,
           0.64865,     0.64965,     0.65065,     0.65165,     0.65265,     0.65365,     0.65465,     0.65566,     0.65666,     0.65766,     0.65866,     0.65966,     0.66066,     0.66166,     0.66266,     0.66366,     0.66466,     0.66567,     0.66667,     0.66767,     0.66867,     0.66967,     0.67067,     0.67167,
           0.67267,     0.67367,     0.67467,     0.67568,     0.67668,     0.67768,     0.67868,     0.67968,     0.68068,     0.68168,     0.68268,     0.68368,     0.68468,     0.68569,     0.68669,     0.68769,     0.68869,     0.68969,     0.69069,     0.69169,     0.69269,     0.69369,     0.69469,      0.6957,
            0.6967,      0.6977,      0.6987,      0.6997,      0.7007,      0.7017,      0.7027,      0.7037,      0.7047,     0.70571,     0.70671,     0.70771,     0.70871,     0.70971,     0.71071,     0.71171,     0.71271,     0.71371,     0.71471,     0.71572,     0.71672,     0.71772,     0.71872,     0.71972,
           0.72072,     0.72172,     0.72272,     0.72372,     0.72472,     0.72573,     0.72673,     0.72773,     0.72873,     0.72973,     0.73073,     0.73173,     0.73273,     0.73373,     0.73473,     0.73574,     0.73674,     0.73774,     0.73874,     0.73974,     0.74074,     0.74174,     0.74274,     0.74374,
           0.74474,     0.74575,     0.74675,     0.74775,     0.74875,     0.74975,     0.75075,     0.75175,     0.75275,     0.75375,     0.75475,     0.75576,     0.75676,     0.75776,     0.75876,     0.75976,     0.76076,     0.76176,     0.76276,     0.76376,     0.76476,     0.76577,     0.76677,     0.76777,
           0.76877,     0.76977,     0.77077,     0.77177,     0.77277,     0.77377,     0.77477,     0.77578,     0.77678,     0.77778,     0.77878,     0.77978,     0.78078,     0.78178,     0.78278,     0.78378,     0.78478,     0.78579,     0.78679,     0.78779,     0.78879,     0.78979,     0.79079,     0.79179,
           0.79279,     0.79379,     0.79479,      0.7958,      0.7968,      0.7978,      0.7988,      0.7998,      0.8008,      0.8018,      0.8028,      0.8038,      0.8048,     0.80581,     0.80681,     0.80781,     0.80881,     0.80981,     0.81081,     0.81181,     0.81281,     0.81381,     0.81481,     0.81582,
           0.81682,     0.81782,     0.81882,     0.81982,     0.82082,     0.82182,     0.82282,     0.82382,     0.82482,     0.82583,     0.82683,     0.82783,     0.82883,     0.82983,     0.83083,     0.83183,     0.83283,     0.83383,     0.83483,     0.83584,     0.83684,     0.83784,     0.83884,     0.83984,
           0.84084,     0.84184,     0.84284,     0.84384,     0.84484,     0.84585,     0.84685,     0.84785,     0.84885,     0.84985,     0.85085,     0.85185,     0.85285,     0.85385,     0.85485,     0.85586,     0.85686,     0.85786,     0.85886,     0.85986,     0.86086,     0.86186,     0.86286,     0.86386,
           0.86486,     0.86587,     0.86687,     0.86787,     0.86887,     0.86987,     0.87087,     0.87187,     0.87287,     0.87387,     0.87487,     0.87588,     0.87688,     0.87788,     0.87888,     0.87988,     0.88088,     0.88188,     0.88288,     0.88388,     0.88488,     0.88589,     0.88689,     0.88789,
           0.88889,     0.88989,     0.89089,     0.89189,     0.89289,     0.89389,     0.89489,      0.8959,      0.8969,      0.8979,      0.8989,      0.8999,      0.9009,      0.9019,      0.9029,      0.9039,      0.9049,     0.90591,     0.90691,     0.90791,     0.90891,     0.90991,     0.91091,     0.91191,
           0.91291,     0.91391,     0.91491,     0.91592,     0.91692,     0.91792,     0.91892,     0.91992,     0.92092,     0.92192,     0.92292,     0.92392,     0.92492,     0.92593,     0.92693,     0.92793,     0.92893,     0.92993,     0.93093,     0.93193,     0.93293,     0.93393,     0.93493,     0.93594,
           0.93694,     0.93794,     0.93894,     0.93994,     0.94094,     0.94194,     0.94294,     0.94394,     0.94494,     0.94595,     0.94695,     0.94795,     0.94895,     0.94995,     0.95095,     0.95195,     0.95295,     0.95395,     0.95495,     0.95596,     0.95696,     0.95796,     0.95896,     0.95996,
           0.96096,     0.96196,     0.96296,     0.96396,     0.96496,     0.96597,     0.96697,     0.96797,     0.96897,     0.96997,     0.97097,     0.97197,     0.97297,     0.97397,     0.97497,     0.97598,     0.97698,     0.97798,     0.97898,     0.97998,     0.98098,     0.98198,     0.98298,     0.98398,
           0.98498,     0.98599,     0.98699,     0.98799,     0.98899,     0.98999,     0.99099,     0.99199,     0.99299,     0.99399,     0.99499,       0.996,       0.997,       0.998,       0.999,           1]), array([[          1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,

In [18]:
model = YOLO("runs/detect/yolo11s_aug_exp/weights/best.pt")

metrics = model.val(data="data.yaml")

print("\n===== YOLO11s + AUGMENTATIONS =====")
print(f"Precision: {metrics.box.mp:.4f}")
print(f"Recall:    {metrics.box.mr:.4f}")
print(f"mAP50:     {metrics.box.map50:.4f}")
print(f"mAP50-95:  {metrics.box.map:.4f}")

results.append({
    "Model": "YOLO11s + Aug",
    "Precision": metrics.box.mp,
    "Recall": metrics.box.mr,
    "mAP50": metrics.box.map50,
    "mAP50-95": metrics.box.map
})

Ultralytics 8.3.0  Python-3.12.9 torch-2.3.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
YOLO11s summary (fused): 238 layers, 9,413,187 parameters, 0 gradients, 21.3 GFLOPs

val: Scanning D:\python\II\dataset\labels\val.cache... 71 images, 0 backgrounds, 0 corrupt: 100%|██████████| 71/71
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 5/5 [00:

                   all         71        119      0.966      0.964      0.987      0.675
Speed: 1.5ms preprocess, 9.2ms inference, 0.0ms loss, 1.2ms postprocess per image
Results saved to runs\detect\val3

===== YOLO11s + AUGMENTATIONS =====
Precision: 0.9663
Recall:    0.9645
mAP50:     0.9872
mAP50-95:  0.6750

Показатели практически не изменелись по сравнению с тем что было до. Небольшие изменения в большую или меньшую сторону и не более.

# Теперь проверим гипотезу 3:

In [19]:
from ultralytics import YOLO

model_freeze = YOLO("yolo11s.pt")

model_freeze.train(
    data="data.yaml",
    epochs=40,
    imgsz=640,
    batch=4,
    workers=0,
    name="yolo11s_freeze_exp",
    exist_ok=True,
    freeze=10  
)

New https://pypi.org/project/ultralytics/8.4.41 available  Update with 'pip install -U ultralytics'
Ultralytics 8.3.0  Python-3.12.9 torch-2.3.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
engine\trainer: task=detect, mode=train, model=yolo11s.pt, data=data.yaml, epochs=40, time=None, patience=100, batch=4, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=0, project=None, name=yolo11s_freeze_exp, exist_ok=True, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=10, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=True, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, copy_paste_mode=flip, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs\detect\yolo11s_freeze_exp
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  3                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  4                  -1  1    103360  ultralytics.nn.modules.block.C3k2            [128, 256, 1, False, 0.25]
  5                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
  6                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1    990976  ultralytics.nn.modules.block.C2PSA           [512, 512, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    443776  ultralytics.nn.modules.block.C3k2            [768, 256, 1, False]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1    127680  ultralytics.nn.modules.block.C3k2            [512, 128, 1, False]
 17                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1    345472  ultralytics.nn.modules.block.C3k2            [384, 256, 1, False]
 20                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1   1511424  ultralytics.nn.modules.block.C3k2            [768, 512, 1, True]
 23        [16, 19, 22]  1    819795  ultralytics.nn.modules.head.Detect           [1, [128, 256, 512]]
YOLO11s summary: 319 layers, 9,428,179 parameters, 9,428,163 gradients, 21.5 GFLOPs

Transferred 493/499 items from pretrained weights
Freezing layer 'model.0.conv.weight'
Freezing layer 'model.0.bn.weight'
Freezing layer 'model.0.bn.bias'
Freezing layer 'model.1.conv.weight'
Freezing layer 'model.1.bn.weight'
Freezing layer 'model.1.bn.bias'
Freezing layer 'model.2.cv1.conv.weight'
Freezing layer 'model.2.cv1.bn.weight'
Freezing layer 'model.2.cv1.bn.bias'
Freezing layer 'model.2.cv2.conv.weight'
Freezing layer 'model.2.cv2.bn.weight'
Freezing layer 'model.2.cv2.bn.bias'
Freezing layer 'model.2.m.0.cv1.conv.weight'
Freezing layer 'model.2.m.0.cv1.bn.weight'
Freezing layer 'model.2.m.0.cv1.bn.bias'
Freezing layer 'model.2.m.0.cv2.conv.weight'
Freezing layer 'model.2.m.0.cv2.bn.weight'
Freezing layer 'model.2.m.0.cv2.bn.bias'
Freezing layer 'model.3.conv.weight'
Freezing layer 'model.3.bn.weight'
Freezing layer 'model.3.bn.bias'
Freezing layer 'model.4.cv1.conv.weight'
Freezing layer 'model.4.cv1.bn.weight'
Freezing layer 'model.4.cv1.bn.bias'
Freezing layer 'model.4.cv2.conv.weight'
Freezing layer 'model.4.cv2.bn.weight'
Freezing layer 'model.4.cv2.bn.bias'
Freezing layer 'model.4.m.0.cv1.conv.weight'
Freezing layer 'model.4.m.0.cv1.bn.weight'
Freezing layer 'model.4.m.0.cv1.bn.bias'
Freezing layer 'model.4.m.0.cv2.conv.weight'
Freezing layer 'model.4.m.0.cv2.bn.weight'
Freezing layer 'model.4.m.0.cv2.bn.bias'
Freezing layer 'model.5.conv.weight'
Freezing layer 'model.5.bn.weight'
Freezing layer 'model.5.bn.bias'
Freezing layer 'model.6.cv1.conv.weight'
Freezing layer 'model.6.cv1.bn.weight'
Freezing layer 'model.6.cv1.bn.bias'
Freezing layer 'model.6.cv2.conv.weight'
Freezing layer 'model.6.cv2.bn.weight'
Freezing layer 'model.6.cv2.bn.bias'
Freezing layer 'model.6.m.0.cv1.conv.weight'
Freezing layer 'model.6.m.0.cv1.bn.weight'
Freezing layer 'model.6.m.0.cv1.bn.bias'
Freezing layer 'model.6.m.0.cv2.conv.weight'
Freezing layer 'model.6.m.0.cv2.bn.weight'
Freezing layer 'model.6.m.0.cv2.bn.bias'
Freezing layer 'model.6.m.0.cv3.conv.weight'
Freezing layer 'model.6.m.0.cv3.bn.weight'
Freezing layer 'model.6.m.0.cv3.bn.bias'
Freezing layer 'model.6.m.0.m.0.cv1.conv.weight'
Freezing layer 'model.6.m.0.m.0.cv1.bn.weight'
Freezing layer 'model.6.m.0.m.0.cv1.bn.bias'
Freezing layer 'model.6.m.0.m.0.cv2.conv.weight'
Freezing layer 'model.6.m.0.m.0.cv2.bn.weight'
Freezing layer 'model.6.m.0.m.0.cv2.bn.bias'
Freezing layer 'model.6.m.0.m.1.cv1.conv.weight'
Freezing layer 'model.6.m.0.m.1.cv1.bn.weight'
Freezing layer 'model.6.m.0.m.1.cv1.bn.bias'
Freezing layer 'model.6.m.0.m.1.cv2.conv.weight'
Freezing layer 'model.6.m.0.m.1.cv2.bn.weight'
Freezing layer 'model.6.m.0.m.1.cv2.bn.bias'
Freezing layer 'model.7.conv.weight'
Freezing layer 'model.7.bn.weight'
Freezing layer 'model.7.bn.bias'
Freezing layer 'model.8.cv1.conv.weight'
Freezing layer 'model.8.cv1.bn.weight'
Freezing layer 'model.8.cv1.bn.bias'
Freezing layer 'model.8.cv2.conv.weight'
Freezing layer 'model.8.cv2.bn.weight'
Freezing layer 'model.8.cv2.bn.bias'
Freezing layer 'model.8.m.0.cv1.conv.weight'
Freezing layer 'model.8.m.0.cv1.bn.weight'
Freezing layer 'model.8.m.0.cv1.bn.bias'
Freezing layer 'model.8.m.0.cv2.conv.weight'
Freezing layer 'model.8.m.0.cv2.bn.weight'
Freezing layer 'model.8.m.0.cv2.bn.bias'
Freezing layer 'model.8.m.0.cv3.conv.weight'
Freezing layer 'model.8.m.0.cv3.bn.weight'
Freezing layer 'model.8.m.0.cv3.bn.bias'
Freezing layer 'model.8.m.0.m.0.cv1.conv.weight'
Freezing layer 'model.8.m.0.m.0.cv1.bn.weight'
Freezing layer 'model.8.m.0.m.0.cv1.bn.bias'
Freezing layer 'model.8.m.0.m.0.cv2.conv.weight'
Freezing layer 'model.8.m.0.m.0.cv2.bn.weight'
Freezing layer 'model.8.m.0.m.0.cv2.bn.bias'
Freezing layer 'model.8.m.0.m.1.cv1.conv.weight'
Freezing layer 'model.8.m.0.m.1.cv1.bn.weight'
Freezing layer 'model.8.m.0.m.1.cv1.bn.bias'
Freezing layer 'model.8.m.0.m.1.cv2.conv.weight'
Freezing layer 'model.8.m.0.m.1.cv2.bn.weight'
Freezing layer 'model.8.m.0.m.1.cv2.bn.bias'
Freezing layer 'model.9.cv1.conv.weight'
Freezing layer 'model.9.cv1.bn.weight'
Freezing layer 'model.9.cv1.bn.bias'
Freezing layer 'model.9.cv2.conv.weight'
Freezing layer 'model.9.cv2.bn.weight'
Freezing layer 'model.9.cv2.bn.bias'
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed

train: Scanning D:\python\II\dataset\labels\train.cache... 284 images, 0 backgrounds, 0 corrupt: 100%|██████████| 2
val: Scanning D:\python\II\dataset\labels\val.cache... 71 images, 0 backgrounds, 0 corrupt: 100%|██████████| 71/71

Plotting labels to runs\detect\yolo11s_freeze_exp\labels.jpg...

optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.002, momentum=0.9) with parameter groups 81 weight(decay=0.0), 88 weight(decay=0.0005), 87 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 0 dataloader workers
Logging results to runs\detect\yolo11s_freeze_exp
Starting training for 40 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       1/40      1.41G      1.482      2.597      1.201         14        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.208      0.876      0.206      0.114

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       2/40     0.935G      1.372      1.077      1.166         10        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.946      0.881      0.953       0.59

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       3/40      0.95G      1.352     0.9584      1.118          9        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.933      0.938      0.955      0.556

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       4/40      0.95G      1.336     0.8431      1.131         20        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.941       0.95      0.973       0.59

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       5/40     0.942G      1.285     0.7791      1.119         10        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119       0.94       0.92      0.974       0.62

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       6/40      0.95G      1.354     0.7542      1.135         18        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.948       0.95      0.984      0.629

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       7/40     0.929G      1.285     0.6934      1.119         10        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.912      0.933      0.963       0.56

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       8/40     0.929G      1.255     0.7026      1.107         18        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.967      0.941      0.973      0.616

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       9/40      0.95G      1.198     0.6392      1.087          9        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.977      0.941      0.979      0.606

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      10/40     0.929G      1.226     0.6643      1.093         11        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.964      0.933      0.981      0.559

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      11/40      0.95G      1.235      0.663      1.095         16        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.991       0.94      0.985      0.596

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      12/40      0.95G      1.193     0.6594      1.083          9        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.937      0.975      0.978      0.598

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      13/40      0.95G      1.201     0.6266      1.074         10        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.982      0.928      0.979       0.62

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      14/40      0.95G      1.126     0.6082      1.053         10        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.958      0.951      0.987      0.653

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      15/40      0.95G      1.145     0.5933      1.059         17        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.974      0.933      0.976      0.631

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      16/40      0.95G      1.132     0.5795      1.056          9        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.957      0.937      0.982      0.652

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      17/40      0.95G      1.121     0.6013      1.052          4        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.974      0.938      0.975      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      18/40      0.95G      1.111     0.5876       1.05         24        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.991      0.939      0.983      0.637

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      19/40      0.95G      1.147     0.5968      1.068         13        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.972      0.958      0.966      0.618

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      20/40      0.95G      1.082     0.5687      1.036         10        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.956      0.966      0.976      0.637

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      21/40      0.95G      1.101     0.5539      1.049         15        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.966      0.964      0.984      0.632

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      22/40     0.929G      1.073     0.5384      1.038         15        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.957      0.975      0.984      0.635

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      23/40     0.929G      1.072     0.5434      1.056          5        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.969      0.966      0.984      0.658

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      24/40     0.929G      1.063     0.5404      1.037         19        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.991      0.958      0.985      0.632

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      25/40     0.929G      1.072     0.5269      1.036         11        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.947      0.975      0.981      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      26/40     0.929G       1.05     0.5254      1.025         10        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.958      0.959      0.981      0.637

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      27/40     0.929G       1.04     0.5316      1.027         10        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.951      0.979      0.985      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      28/40     0.929G      1.057     0.5238      1.027          8        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.954      0.975      0.985      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      29/40     0.929G      1.005     0.5138      1.002          8        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.966      0.951      0.977      0.643

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      30/40     0.927G       1.01     0.4927      1.001         12        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.991      0.946      0.978      0.661

Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      31/40     0.927G      1.042     0.5027      1.035          5        640: 100%|██████████| 71/71 [00:08<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.941      0.935      0.978      0.625

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      32/40     0.929G      0.983     0.4852      1.013          4        640: 100%|██████████| 71/71 [00:08<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.927      0.959       0.98      0.653

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      33/40     0.929G     0.9781     0.4833      1.022          4        640: 100%|██████████| 71/71 [00:08<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119       0.94      0.966      0.983      0.658

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      34/40     0.929G      1.008     0.4773      1.007          8        640: 100%|██████████| 71/71 [00:08<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.966       0.95      0.982      0.661

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      35/40     0.929G     0.9894     0.4786      1.001          7        640: 100%|██████████| 71/71 [00:08<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.975      0.966      0.989      0.664

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      36/40     0.929G     0.9649     0.4726      1.007          4        640: 100%|██████████| 71/71 [00:08<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.971      0.958      0.977      0.656

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      37/40     0.946G      0.967     0.4584      1.013          2        640: 100%|██████████| 71/71 [00:08<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.974       0.96      0.982      0.661

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      38/40      0.95G     0.9578     0.4482      1.002          5        640: 100%|██████████| 71/71 [00:08<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.973      0.958      0.982      0.679

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      39/40     0.929G     0.9265      0.442     0.9738          5        640: 100%|██████████| 71/71 [00:08<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.966      0.956      0.982      0.674

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      40/40     0.929G     0.9303     0.4419     0.9745          4        640: 100%|██████████| 71/71 [00:08<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.951      0.958      0.981      0.665

40 epochs completed in 0.122 hours.
Optimizer stripped from runs\detect\yolo11s_freeze_exp\weights\last.pt, 19.2MB
Optimizer stripped from runs\detect\yolo11s_freeze_exp\weights\best.pt, 19.2MB

Validating runs\detect\yolo11s_freeze_exp\weights\best.pt...
Ultralytics 8.3.0  Python-3.12.9 torch-2.3.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
YOLO11s summary (fused): 238 layers, 9,413,187 parameters, 0 gradients, 21.3 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.973      0.958      0.987      0.679
Speed: 0.4ms preprocess, 4.9ms inference, 0.0ms loss, 1.0ms postprocess per image
Results saved to runs\detect\yolo11s_freeze_exp

ultralytics.utils.metrics.DetMetrics object with attributes:

ap_class_index: array([0])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x00000290B1515190>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,
           0.43243,     0.43343,     0.43443,     0.43544,     0.43644,     0.43744,     0.43844,     0.43944,     0.44044,     0.44144,     0.44244,     0.44344,     0.44444,     0.44545,     0.44645,     0.44745,     0.44845,     0.44945,     0.45045,     0.45145,     0.45245,     0.45345,     0.45445,     0.45546,
           0.45646,     0.45746,     0.45846,     0.45946,     0.46046,     0.46146,     0.46246,     0.46346,     0.46446,     0.46547,     0.46647,     0.46747,     0.46847,     0.46947,     0.47047,     0.47147,     0.47247,     0.47347,     0.47447,     0.47548,     0.47648,     0.47748,     0.47848,     0.47948,
           0.48048,     0.48148,     0.48248,     0.48348,     0.48448,     0.48549,     0.48649,     0.48749,     0.48849,     0.48949,     0.49049,     0.49149,     0.49249,     0.49349,     0.49449,      0.4955,      0.4965,      0.4975,      0.4985,      0.4995,      0.5005,      0.5015,      0.5025,      0.5035,
            0.5045,     0.50551,     0.50651,     0.50751,     0.50851,     0.50951,     0.51051,     0.51151,     0.51251,     0.51351,     0.51451,     0.51552,     0.51652,     0.51752,     0.51852,     0.51952,     0.52052,     0.52152,     0.52252,     0.52352,     0.52452,     0.52553,     0.52653,     0.52753,
           0.52853,     0.52953,     0.53053,     0.53153,     0.53253,     0.53353,     0.53453,     0.53554,     0.53654,     0.53754,     0.53854,     0.53954,     0.54054,     0.54154,     0.54254,     0.54354,     0.54454,     0.54555,     0.54655,     0.54755,     0.54855,     0.54955,     0.55055,     0.55155,
           0.55255,     0.55355,     0.55455,     0.55556,     0.55656,     0.55756,     0.55856,     0.55956,     0.56056,     0.56156,     0.56256,     0.56356,     0.56456,     0.56557,     0.56657,     0.56757,     0.56857,     0.56957,     0.57057,     0.57157,     0.57257,     0.57357,     0.57457,     0.57558,
           0.57658,     0.57758,     0.57858,     0.57958,     0.58058,     0.58158,     0.58258,     0.58358,     0.58458,     0.58559,     0.58659,     0.58759,     0.58859,     0.58959,     0.59059,     0.59159,     0.59259,     0.59359,     0.59459,      0.5956,      0.5966,      0.5976,      0.5986,      0.5996,
            0.6006,      0.6016,      0.6026,      0.6036,      0.6046,     0.60561,     0.60661,     0.60761,     0.60861,     0.60961,     0.61061,     0.61161,     0.61261,     0.61361,     0.61461,     0.61562,     0.61662,     0.61762,     0.61862,     0.61962,     0.62062,     0.62162,     0.62262,     0.62362,
           0.62462,     0.62563,     0.62663,     0.62763,     0.62863,     0.62963,     0.63063,     0.63163,     0.63263,     0.63363,     0.63463,     0.63564,     0.63664,     0.63764,     0.63864,     0.63964,     0.64064,     0.64164,     0.64264,     0.64364,     0.64464,     0.64565,     0.64665,     0.64765,
           0.64865,     0.64965,     0.65065,     0.65165,     0.65265,     0.65365,     0.65465,     0.65566,     0.65666,     0.65766,     0.65866,     0.65966,     0.66066,     0.66166,     0.66266,     0.66366,     0.66466,     0.66567,     0.66667,     0.66767,     0.66867,     0.66967,     0.67067,     0.67167,
           0.67267,     0.67367,     0.67467,     0.67568,     0.67668,     0.67768,     0.67868,     0.67968,     0.68068,     0.68168,     0.68268,     0.68368,     0.68468,     0.68569,     0.68669,     0.68769,     0.68869,     0.68969,     0.69069,     0.69169,     0.69269,     0.69369,     0.69469,      0.6957,
            0.6967,      0.6977,      0.6987,      0.6997,      0.7007,      0.7017,      0.7027,      0.7037,      0.7047,     0.70571,     0.70671,     0.70771,     0.70871,     0.70971,     0.71071,     0.71171,     0.71271,     0.71371,     0.71471,     0.71572,     0.71672,     0.71772,     0.71872,     0.71972,
           0.72072,     0.72172,     0.72272,     0.72372,     0.72472,     0.72573,     0.72673,     0.72773,     0.72873,     0.72973,     0.73073,     0.73173,     0.73273,     0.73373,     0.73473,     0.73574,     0.73674,     0.73774,     0.73874,     0.73974,     0.74074,     0.74174,     0.74274,     0.74374,
           0.74474,     0.74575,     0.74675,     0.74775,     0.74875,     0.74975,     0.75075,     0.75175,     0.75275,     0.75375,     0.75475,     0.75576,     0.75676,     0.75776,     0.75876,     0.75976,     0.76076,     0.76176,     0.76276,     0.76376,     0.76476,     0.76577,     0.76677,     0.76777,
           0.76877,     0.76977,     0.77077,     0.77177,     0.77277,     0.77377,     0.77477,     0.77578,     0.77678,     0.77778,     0.77878,     0.77978,     0.78078,     0.78178,     0.78278,     0.78378,     0.78478,     0.78579,     0.78679,     0.78779,     0.78879,     0.78979,     0.79079,     0.79179,
           0.79279,     0.79379,     0.79479,      0.7958,      0.7968,      0.7978,      0.7988,      0.7998,      0.8008,      0.8018,      0.8028,      0.8038,      0.8048,     0.80581,     0.80681,     0.80781,     0.80881,     0.80981,     0.81081,     0.81181,     0.81281,     0.81381,     0.81481,     0.81582,
           0.81682,     0.81782,     0.81882,     0.81982,     0.82082,     0.82182,     0.82282,     0.82382,     0.82482,     0.82583,     0.82683,     0.82783,     0.82883,     0.82983,     0.83083,     0.83183,     0.83283,     0.83383,     0.83483,     0.83584,     0.83684,     0.83784,     0.83884,     0.83984,
           0.84084,     0.84184,     0.84284,     0.84384,     0.84484,     0.84585,     0.84685,     0.84785,     0.84885,     0.84985,     0.85085,     0.85185,     0.85285,     0.85385,     0.85485,     0.85586,     0.85686,     0.85786,     0.85886,     0.85986,     0.86086,     0.86186,     0.86286,     0.86386,
           0.86486,     0.86587,     0.86687,     0.86787,     0.86887,     0.86987,     0.87087,     0.87187,     0.87287,     0.87387,     0.87487,     0.87588,     0.87688,     0.87788,     0.87888,     0.87988,     0.88088,     0.88188,     0.88288,     0.88388,     0.88488,     0.88589,     0.88689,     0.88789,
           0.88889,     0.88989,     0.89089,     0.89189,     0.89289,     0.89389,     0.89489,      0.8959,      0.8969,      0.8979,      0.8989,      0.8999,      0.9009,      0.9019,      0.9029,      0.9039,      0.9049,     0.90591,     0.90691,     0.90791,     0.90891,     0.90991,     0.91091,     0.91191,
           0.91291,     0.91391,     0.91491,     0.91592,     0.91692,     0.91792,     0.91892,     0.91992,     0.92092,     0.92192,     0.92292,     0.92392,     0.92492,     0.92593,     0.92693,     0.92793,     0.92893,     0.92993,     0.93093,     0.93193,     0.93293,     0.93393,     0.93493,     0.93594,
           0.93694,     0.93794,     0.93894,     0.93994,     0.94094,     0.94194,     0.94294,     0.94394,     0.94494,     0.94595,     0.94695,     0.94795,     0.94895,     0.94995,     0.95095,     0.95195,     0.95295,     0.95395,     0.95495,     0.95596,     0.95696,     0.95796,     0.95896,     0.95996,
           0.96096,     0.96196,     0.96296,     0.96396,     0.96496,     0.96597,     0.96697,     0.96797,     0.96897,     0.96997,     0.97097,     0.97197,     0.97297,     0.97397,     0.97497,     0.97598,     0.97698,     0.97798,     0.97898,     0.97998,     0.98098,     0.98198,     0.98298,     0.98398,
           0.98498,     0.98599,     0.98699,     0.98799,     0.98899,     0.98999,     0.99099,     0.99199,     0.99299,     0.99399,     0.99499,       0.996,       0.997,       0.998,       0.999,           1]), array([[          1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,

In [20]:
from ultralytics import YOLO

model = YOLO("runs/detect/yolo11s_freeze_exp/weights/best.pt")

metrics = model.val(data="data.yaml")

print("\n===== YOLO11s + FREEZE =====")
print(f"Precision: {metrics.box.mp:.4f}")
print(f"Recall:    {metrics.box.mr:.4f}")
print(f"mAP50:     {metrics.box.map50:.4f}")
print(f"mAP50-95:  {metrics.box.map:.4f}")

results.append({
    "Model": "YOLO11s + Freeze",
    "Precision": metrics.box.mp,
    "Recall": metrics.box.mr,
    "mAP50": metrics.box.map50,
    "mAP50-95": metrics.box.map
})

Ultralytics 8.3.0  Python-3.12.9 torch-2.3.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
YOLO11s summary (fused): 238 layers, 9,413,187 parameters, 0 gradients, 21.3 GFLOPs

val: Scanning D:\python\II\dataset\labels\val.cache... 71 images, 0 backgrounds, 0 corrupt: 100%|██████████| 71/71
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 5/5 [00:

                   all         71        119      0.973      0.958      0.987      0.681
Speed: 0.9ms preprocess, 8.8ms inference, 0.0ms loss, 1.6ms postprocess per image
Results saved to runs\detect\val4

===== YOLO11s + FREEZE =====
Precision: 0.9726
Recall:    0.9580
mAP50:     0.9868
mAP50-95:  0.6808

Мы получили наивысшие показатели mAP50-95, но значительной прибавки мы так и не получили. Я пробовал менять значения freeze, но значительных изменений это тоже не дало. Теперь попробуем совместить все 3 гипотезы:

In [21]:
model_combo = YOLO("yolo11s.pt")

model_combo.train(
    data="data.yaml",
    epochs=40,
    imgsz=640,
    batch=4,
    workers=0,
    name="yolo11s_aug_freeze_exp",
    exist_ok=True,

    mosaic=1.0,
    mixup=0.2,
    hsv_h=0.015,
    hsv_s=0.7,
    hsv_v=0.4,
    fliplr=0.5,

    freeze=10
)

New https://pypi.org/project/ultralytics/8.4.41 available  Update with 'pip install -U ultralytics'
Ultralytics 8.3.0  Python-3.12.9 torch-2.3.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
engine\trainer: task=detect, mode=train, model=yolo11s.pt, data=data.yaml, epochs=40, time=None, patience=100, batch=4, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=0, project=None, name=yolo11s_aug_freeze_exp, exist_ok=True, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=10, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=True, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.2, copy_paste=0.0, copy_paste_mode=flip, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs\detect\yolo11s_aug_freeze_exp
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  3                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  4                  -1  1    103360  ultralytics.nn.modules.block.C3k2            [128, 256, 1, False, 0.25]
  5                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
  6                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1    990976  ultralytics.nn.modules.block.C2PSA           [512, 512, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    443776  ultralytics.nn.modules.block.C3k2            [768, 256, 1, False]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1    127680  ultralytics.nn.modules.block.C3k2            [512, 128, 1, False]
 17                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1    345472  ultralytics.nn.modules.block.C3k2            [384, 256, 1, False]
 20                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1   1511424  ultralytics.nn.modules.block.C3k2            [768, 512, 1, True]
 23        [16, 19, 22]  1    819795  ultralytics.nn.modules.head.Detect           [1, [128, 256, 512]]
YOLO11s summary: 319 layers, 9,428,179 parameters, 9,428,163 gradients, 21.5 GFLOPs

Transferred 493/499 items from pretrained weights
Freezing layer 'model.0.conv.weight'
Freezing layer 'model.0.bn.weight'
Freezing layer 'model.0.bn.bias'
Freezing layer 'model.1.conv.weight'
Freezing layer 'model.1.bn.weight'
Freezing layer 'model.1.bn.bias'
Freezing layer 'model.2.cv1.conv.weight'
Freezing layer 'model.2.cv1.bn.weight'
Freezing layer 'model.2.cv1.bn.bias'
Freezing layer 'model.2.cv2.conv.weight'
Freezing layer 'model.2.cv2.bn.weight'
Freezing layer 'model.2.cv2.bn.bias'
Freezing layer 'model.2.m.0.cv1.conv.weight'
Freezing layer 'model.2.m.0.cv1.bn.weight'
Freezing layer 'model.2.m.0.cv1.bn.bias'
Freezing layer 'model.2.m.0.cv2.conv.weight'
Freezing layer 'model.2.m.0.cv2.bn.weight'
Freezing layer 'model.2.m.0.cv2.bn.bias'
Freezing layer 'model.3.conv.weight'
Freezing layer 'model.3.bn.weight'
Freezing layer 'model.3.bn.bias'
Freezing layer 'model.4.cv1.conv.weight'
Freezing layer 'model.4.cv1.bn.weight'
Freezing layer 'model.4.cv1.bn.bias'
Freezing layer 'model.4.cv2.conv.weight'
Freezing layer 'model.4.cv2.bn.weight'
Freezing layer 'model.4.cv2.bn.bias'
Freezing layer 'model.4.m.0.cv1.conv.weight'
Freezing layer 'model.4.m.0.cv1.bn.weight'
Freezing layer 'model.4.m.0.cv1.bn.bias'
Freezing layer 'model.4.m.0.cv2.conv.weight'
Freezing layer 'model.4.m.0.cv2.bn.weight'
Freezing layer 'model.4.m.0.cv2.bn.bias'
Freezing layer 'model.5.conv.weight'
Freezing layer 'model.5.bn.weight'
Freezing layer 'model.5.bn.bias'
Freezing layer 'model.6.cv1.conv.weight'
Freezing layer 'model.6.cv1.bn.weight'
Freezing layer 'model.6.cv1.bn.bias'
Freezing layer 'model.6.cv2.conv.weight'
Freezing layer 'model.6.cv2.bn.weight'
Freezing layer 'model.6.cv2.bn.bias'
Freezing layer 'model.6.m.0.cv1.conv.weight'
Freezing layer 'model.6.m.0.cv1.bn.weight'
Freezing layer 'model.6.m.0.cv1.bn.bias'
Freezing layer 'model.6.m.0.cv2.conv.weight'
Freezing layer 'model.6.m.0.cv2.bn.weight'
Freezing layer 'model.6.m.0.cv2.bn.bias'
Freezing layer 'model.6.m.0.cv3.conv.weight'
Freezing layer 'model.6.m.0.cv3.bn.weight'
Freezing layer 'model.6.m.0.cv3.bn.bias'
Freezing layer 'model.6.m.0.m.0.cv1.conv.weight'
Freezing layer 'model.6.m.0.m.0.cv1.bn.weight'
Freezing layer 'model.6.m.0.m.0.cv1.bn.bias'
Freezing layer 'model.6.m.0.m.0.cv2.conv.weight'
Freezing layer 'model.6.m.0.m.0.cv2.bn.weight'
Freezing layer 'model.6.m.0.m.0.cv2.bn.bias'
Freezing layer 'model.6.m.0.m.1.cv1.conv.weight'
Freezing layer 'model.6.m.0.m.1.cv1.bn.weight'
Freezing layer 'model.6.m.0.m.1.cv1.bn.bias'
Freezing layer 'model.6.m.0.m.1.cv2.conv.weight'
Freezing layer 'model.6.m.0.m.1.cv2.bn.weight'
Freezing layer 'model.6.m.0.m.1.cv2.bn.bias'
Freezing layer 'model.7.conv.weight'
Freezing layer 'model.7.bn.weight'
Freezing layer 'model.7.bn.bias'
Freezing layer 'model.8.cv1.conv.weight'
Freezing layer 'model.8.cv1.bn.weight'
Freezing layer 'model.8.cv1.bn.bias'
Freezing layer 'model.8.cv2.conv.weight'
Freezing layer 'model.8.cv2.bn.weight'
Freezing layer 'model.8.cv2.bn.bias'
Freezing layer 'model.8.m.0.cv1.conv.weight'
Freezing layer 'model.8.m.0.cv1.bn.weight'
Freezing layer 'model.8.m.0.cv1.bn.bias'
Freezing layer 'model.8.m.0.cv2.conv.weight'
Freezing layer 'model.8.m.0.cv2.bn.weight'
Freezing layer 'model.8.m.0.cv2.bn.bias'
Freezing layer 'model.8.m.0.cv3.conv.weight'
Freezing layer 'model.8.m.0.cv3.bn.weight'
Freezing layer 'model.8.m.0.cv3.bn.bias'
Freezing layer 'model.8.m.0.m.0.cv1.conv.weight'
Freezing layer 'model.8.m.0.m.0.cv1.bn.weight'
Freezing layer 'model.8.m.0.m.0.cv1.bn.bias'
Freezing layer 'model.8.m.0.m.0.cv2.conv.weight'
Freezing layer 'model.8.m.0.m.0.cv2.bn.weight'
Freezing layer 'model.8.m.0.m.0.cv2.bn.bias'
Freezing layer 'model.8.m.0.m.1.cv1.conv.weight'
Freezing layer 'model.8.m.0.m.1.cv1.bn.weight'
Freezing layer 'model.8.m.0.m.1.cv1.bn.bias'
Freezing layer 'model.8.m.0.m.1.cv2.conv.weight'
Freezing layer 'model.8.m.0.m.1.cv2.bn.weight'
Freezing layer 'model.8.m.0.m.1.cv2.bn.bias'
Freezing layer 'model.9.cv1.conv.weight'
Freezing layer 'model.9.cv1.bn.weight'
Freezing layer 'model.9.cv1.bn.bias'
Freezing layer 'model.9.cv2.conv.weight'
Freezing layer 'model.9.cv2.bn.weight'
Freezing layer 'model.9.cv2.bn.bias'
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed

train: Scanning D:\python\II\dataset\labels\train.cache... 284 images, 0 backgrounds, 0 corrupt: 100%|██████████| 2
val: Scanning D:\python\II\dataset\labels\val.cache... 71 images, 0 backgrounds, 0 corrupt: 100%|██████████| 71/71

Plotting labels to runs\detect\yolo11s_aug_freeze_exp\labels.jpg...

optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.002, momentum=0.9) with parameter groups 81 weight(decay=0.0), 88 weight(decay=0.0005), 87 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 0 dataloader workers
Logging results to runs\detect\yolo11s_aug_freeze_exp
Starting training for 40 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       1/40      1.55G      1.514      2.626      1.234          7        640: 100%|██████████| 71/71 [00:11<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.895      0.908      0.956      0.589

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       2/40      1.08G      1.433      1.222      1.206          7        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.947      0.906      0.955      0.592

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       3/40      1.08G      1.387      1.082       1.17         17        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.974      0.916      0.985      0.554

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       4/40      1.07G      1.397     0.9608      1.166         11        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.977      0.941      0.974        0.6

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       5/40      1.07G      1.351     0.8422       1.17         18        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.966      0.944       0.98      0.603

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       6/40      1.07G      1.351     0.8152      1.182         12        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.991      0.923      0.966      0.606

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       7/40      1.07G      1.311      0.781      1.172         13        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.965      0.928      0.985      0.614

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       8/40      1.07G      1.277     0.7301      1.145          6        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.969      0.941      0.988      0.621

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       9/40      1.07G      1.284      0.732      1.152         12        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.966      0.948      0.983      0.626

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      10/40      1.09G      1.281     0.7391      1.143         33        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.974      0.931      0.978      0.632

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      11/40      1.07G      1.246     0.7078       1.13         22        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.945      0.933      0.979      0.652

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      12/40      1.07G      1.239     0.7244      1.126          4        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.974      0.947       0.99      0.646

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      13/40      1.07G       1.18     0.6485      1.102         26        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.983      0.952      0.988      0.649

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      14/40      1.07G      1.217     0.6532      1.129         24        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.966      0.975      0.992      0.619

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      15/40      1.09G      1.203     0.6316      1.108         13        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.975       0.97      0.992      0.613

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      16/40      1.09G      1.178     0.6141      1.098         27        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.978      0.958      0.989      0.636

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      17/40      1.09G      1.171     0.6204      1.083         12        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119       0.99      0.941      0.992      0.635

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      18/40      1.09G      1.152     0.5989      1.084          9        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.983      0.957      0.989      0.635

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      19/40      1.09G      1.105     0.5802      1.062         15        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.976      0.958      0.989      0.655

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      20/40      1.09G      1.153     0.6026      1.084         16        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119       0.98      0.966      0.982      0.641

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      21/40      1.07G      1.131       0.59      1.084         19        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.986      0.966      0.992      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      22/40      1.09G      1.131     0.5734      1.063         12        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.989      0.975      0.993      0.656

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      23/40      1.07G      1.108     0.5545      1.059         13        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.983      0.965      0.984      0.659

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      24/40      1.09G      1.128       0.58       1.08         19        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.988      0.966      0.985       0.64

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      25/40      1.07G      1.108     0.5631      1.047         22        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.982      0.942      0.992      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      26/40      1.07G      1.149     0.5764       1.07          7        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.976      0.966      0.993      0.656

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      27/40      1.07G      1.097     0.5498      1.037         18        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.958      0.983      0.992      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      28/40      1.07G      1.083     0.5468      1.053         18        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.973      0.975      0.993      0.675

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      29/40      1.07G      1.092      0.547      1.044         14        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.991      0.955      0.993      0.679

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      30/40      1.09G      1.076      0.549      1.045          7        640: 100%|██████████| 71/71 [00:10<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.974       0.96      0.993      0.654

Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      31/40      1.07G       1.05     0.5124      1.045          5        640: 100%|██████████| 71/71 [00:08<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.983      0.945      0.984      0.687

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      32/40      1.09G      1.031     0.4932      1.023          3        640: 100%|██████████| 71/71 [00:08<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.982      0.931      0.986      0.642

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      33/40      1.09G      1.021     0.4908      1.042          4        640: 100%|██████████| 71/71 [00:08<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.987      0.933      0.978      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      34/40      1.09G     0.9966     0.4812      1.009          7        640: 100%|██████████| 71/71 [00:08<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.997      0.941      0.984      0.679

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      35/40      1.07G     0.9842      0.476      1.022          8        640: 100%|██████████| 71/71 [00:08<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.974      0.946      0.984      0.668

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      36/40      1.09G     0.9722      0.477     0.9912          5        640: 100%|██████████| 71/71 [00:08<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.993      0.924      0.991      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      37/40      1.09G     0.9842      0.468      1.005          3        640: 100%|██████████| 71/71 [00:08<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.976      0.941      0.984      0.675

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      38/40      1.07G     0.9742       0.45      1.005          5        640: 100%|██████████| 71/71 [00:08<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119       0.96       0.95      0.984      0.668

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      39/40      1.07G      0.965     0.4548      1.009          5        640: 100%|██████████| 71/71 [00:09<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.983      0.944      0.984      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      40/40      1.07G     0.9271     0.4445     0.9821          3        640: 100%|██████████| 71/71 [00:08<00:00,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.974       0.95      0.985      0.665

40 epochs completed in 0.126 hours.
Optimizer stripped from runs\detect\yolo11s_aug_freeze_exp\weights\last.pt, 19.2MB
Optimizer stripped from runs\detect\yolo11s_aug_freeze_exp\weights\best.pt, 19.2MB

Validating runs\detect\yolo11s_aug_freeze_exp\weights\best.pt...
Ultralytics 8.3.0  Python-3.12.9 torch-2.3.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
YOLO11s summary (fused): 238 layers, 9,413,187 parameters, 0 gradients, 21.3 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:

                   all         71        119      0.983      0.945      0.984      0.687
Speed: 0.4ms preprocess, 4.9ms inference, 0.0ms loss, 0.9ms postprocess per image
Results saved to runs\detect\yolo11s_aug_freeze_exp

ultralytics.utils.metrics.DetMetrics object with attributes:

ap_class_index: array([0])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x00000290B1665AF0>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,
           0.43243,     0.43343,     0.43443,     0.43544,     0.43644,     0.43744,     0.43844,     0.43944,     0.44044,     0.44144,     0.44244,     0.44344,     0.44444,     0.44545,     0.44645,     0.44745,     0.44845,     0.44945,     0.45045,     0.45145,     0.45245,     0.45345,     0.45445,     0.45546,
           0.45646,     0.45746,     0.45846,     0.45946,     0.46046,     0.46146,     0.46246,     0.46346,     0.46446,     0.46547,     0.46647,     0.46747,     0.46847,     0.46947,     0.47047,     0.47147,     0.47247,     0.47347,     0.47447,     0.47548,     0.47648,     0.47748,     0.47848,     0.47948,
           0.48048,     0.48148,     0.48248,     0.48348,     0.48448,     0.48549,     0.48649,     0.48749,     0.48849,     0.48949,     0.49049,     0.49149,     0.49249,     0.49349,     0.49449,      0.4955,      0.4965,      0.4975,      0.4985,      0.4995,      0.5005,      0.5015,      0.5025,      0.5035,
            0.5045,     0.50551,     0.50651,     0.50751,     0.50851,     0.50951,     0.51051,     0.51151,     0.51251,     0.51351,     0.51451,     0.51552,     0.51652,     0.51752,     0.51852,     0.51952,     0.52052,     0.52152,     0.52252,     0.52352,     0.52452,     0.52553,     0.52653,     0.52753,
           0.52853,     0.52953,     0.53053,     0.53153,     0.53253,     0.53353,     0.53453,     0.53554,     0.53654,     0.53754,     0.53854,     0.53954,     0.54054,     0.54154,     0.54254,     0.54354,     0.54454,     0.54555,     0.54655,     0.54755,     0.54855,     0.54955,     0.55055,     0.55155,
           0.55255,     0.55355,     0.55455,     0.55556,     0.55656,     0.55756,     0.55856,     0.55956,     0.56056,     0.56156,     0.56256,     0.56356,     0.56456,     0.56557,     0.56657,     0.56757,     0.56857,     0.56957,     0.57057,     0.57157,     0.57257,     0.57357,     0.57457,     0.57558,
           0.57658,     0.57758,     0.57858,     0.57958,     0.58058,     0.58158,     0.58258,     0.58358,     0.58458,     0.58559,     0.58659,     0.58759,     0.58859,     0.58959,     0.59059,     0.59159,     0.59259,     0.59359,     0.59459,      0.5956,      0.5966,      0.5976,      0.5986,      0.5996,
            0.6006,      0.6016,      0.6026,      0.6036,      0.6046,     0.60561,     0.60661,     0.60761,     0.60861,     0.60961,     0.61061,     0.61161,     0.61261,     0.61361,     0.61461,     0.61562,     0.61662,     0.61762,     0.61862,     0.61962,     0.62062,     0.62162,     0.62262,     0.62362,
           0.62462,     0.62563,     0.62663,     0.62763,     0.62863,     0.62963,     0.63063,     0.63163,     0.63263,     0.63363,     0.63463,     0.63564,     0.63664,     0.63764,     0.63864,     0.63964,     0.64064,     0.64164,     0.64264,     0.64364,     0.64464,     0.64565,     0.64665,     0.64765,
           0.64865,     0.64965,     0.65065,     0.65165,     0.65265,     0.65365,     0.65465,     0.65566,     0.65666,     0.65766,     0.65866,     0.65966,     0.66066,     0.66166,     0.66266,     0.66366,     0.66466,     0.66567,     0.66667,     0.66767,     0.66867,     0.66967,     0.67067,     0.67167,
           0.67267,     0.67367,     0.67467,     0.67568,     0.67668,     0.67768,     0.67868,     0.67968,     0.68068,     0.68168,     0.68268,     0.68368,     0.68468,     0.68569,     0.68669,     0.68769,     0.68869,     0.68969,     0.69069,     0.69169,     0.69269,     0.69369,     0.69469,      0.6957,
            0.6967,      0.6977,      0.6987,      0.6997,      0.7007,      0.7017,      0.7027,      0.7037,      0.7047,     0.70571,     0.70671,     0.70771,     0.70871,     0.70971,     0.71071,     0.71171,     0.71271,     0.71371,     0.71471,     0.71572,     0.71672,     0.71772,     0.71872,     0.71972,
           0.72072,     0.72172,     0.72272,     0.72372,     0.72472,     0.72573,     0.72673,     0.72773,     0.72873,     0.72973,     0.73073,     0.73173,     0.73273,     0.73373,     0.73473,     0.73574,     0.73674,     0.73774,     0.73874,     0.73974,     0.74074,     0.74174,     0.74274,     0.74374,
           0.74474,     0.74575,     0.74675,     0.74775,     0.74875,     0.74975,     0.75075,     0.75175,     0.75275,     0.75375,     0.75475,     0.75576,     0.75676,     0.75776,     0.75876,     0.75976,     0.76076,     0.76176,     0.76276,     0.76376,     0.76476,     0.76577,     0.76677,     0.76777,
           0.76877,     0.76977,     0.77077,     0.77177,     0.77277,     0.77377,     0.77477,     0.77578,     0.77678,     0.77778,     0.77878,     0.77978,     0.78078,     0.78178,     0.78278,     0.78378,     0.78478,     0.78579,     0.78679,     0.78779,     0.78879,     0.78979,     0.79079,     0.79179,
           0.79279,     0.79379,     0.79479,      0.7958,      0.7968,      0.7978,      0.7988,      0.7998,      0.8008,      0.8018,      0.8028,      0.8038,      0.8048,     0.80581,     0.80681,     0.80781,     0.80881,     0.80981,     0.81081,     0.81181,     0.81281,     0.81381,     0.81481,     0.81582,
           0.81682,     0.81782,     0.81882,     0.81982,     0.82082,     0.82182,     0.82282,     0.82382,     0.82482,     0.82583,     0.82683,     0.82783,     0.82883,     0.82983,     0.83083,     0.83183,     0.83283,     0.83383,     0.83483,     0.83584,     0.83684,     0.83784,     0.83884,     0.83984,
           0.84084,     0.84184,     0.84284,     0.84384,     0.84484,     0.84585,     0.84685,     0.84785,     0.84885,     0.84985,     0.85085,     0.85185,     0.85285,     0.85385,     0.85485,     0.85586,     0.85686,     0.85786,     0.85886,     0.85986,     0.86086,     0.86186,     0.86286,     0.86386,
           0.86486,     0.86587,     0.86687,     0.86787,     0.86887,     0.86987,     0.87087,     0.87187,     0.87287,     0.87387,     0.87487,     0.87588,     0.87688,     0.87788,     0.87888,     0.87988,     0.88088,     0.88188,     0.88288,     0.88388,     0.88488,     0.88589,     0.88689,     0.88789,
           0.88889,     0.88989,     0.89089,     0.89189,     0.89289,     0.89389,     0.89489,      0.8959,      0.8969,      0.8979,      0.8989,      0.8999,      0.9009,      0.9019,      0.9029,      0.9039,      0.9049,     0.90591,     0.90691,     0.90791,     0.90891,     0.90991,     0.91091,     0.91191,
           0.91291,     0.91391,     0.91491,     0.91592,     0.91692,     0.91792,     0.91892,     0.91992,     0.92092,     0.92192,     0.92292,     0.92392,     0.92492,     0.92593,     0.92693,     0.92793,     0.92893,     0.92993,     0.93093,     0.93193,     0.93293,     0.93393,     0.93493,     0.93594,
           0.93694,     0.93794,     0.93894,     0.93994,     0.94094,     0.94194,     0.94294,     0.94394,     0.94494,     0.94595,     0.94695,     0.94795,     0.94895,     0.94995,     0.95095,     0.95195,     0.95295,     0.95395,     0.95495,     0.95596,     0.95696,     0.95796,     0.95896,     0.95996,
           0.96096,     0.96196,     0.96296,     0.96396,     0.96496,     0.96597,     0.96697,     0.96797,     0.96897,     0.96997,     0.97097,     0.97197,     0.97297,     0.97397,     0.97497,     0.97598,     0.97698,     0.97798,     0.97898,     0.97998,     0.98098,     0.98198,     0.98298,     0.98398,
           0.98498,     0.98599,     0.98699,     0.98799,     0.98899,     0.98999,     0.99099,     0.99199,     0.99299,     0.99399,     0.99499,       0.996,       0.997,       0.998,       0.999,           1]), array([[          1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,           1,

In [22]:
model = YOLO("runs/detect/yolo11s_aug_freeze_exp/weights/best.pt")
metrics = model.val(data="data.yaml")

print("\n===== YOLO11s + AUG + FREEZE =====")
print(f"Precision: {metrics.box.mp:.4f}")
print(f"Recall:    {metrics.box.mr:.4f}")
print(f"mAP50:     {metrics.box.map50:.4f}")
print(f"mAP50-95:  {metrics.box.map:.4f}")

results.append({
    "Model": "YOLO11s + Aug + Freeze",
    "Precision": metrics.box.mp,
    "Recall": metrics.box.mr,
    "mAP50": metrics.box.map50,
    "mAP50-95": metrics.box.map
})

Ultralytics 8.3.0  Python-3.12.9 torch-2.3.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
YOLO11s summary (fused): 238 layers, 9,413,187 parameters, 0 gradients, 21.3 GFLOPs

val: Scanning D:\python\II\dataset\labels\val.cache... 71 images, 0 backgrounds, 0 corrupt: 100%|██████████| 71/71
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 5/5 [00:

                   all         71        119      0.966      0.966      0.984      0.689
Speed: 1.0ms preprocess, 8.5ms inference, 0.0ms loss, 1.8ms postprocess per image
Results saved to runs\detect\val5

===== YOLO11s + AUG + FREEZE =====
Precision: 0.9657
Recall:    0.9664
mAP50:     0.9839
mAP50-95:  0.6890

Сравниваем итоговые результаты:

In [23]:
import pandas as pd

df = pd.DataFrame(results)
df

                    Model  Precision    Recall     mAP50  mAP50-95
0                 YOLO11n   0.984121  0.949580  0.973670  0.654472
1                 YOLO11s   0.958292  0.965390  0.976780  0.679280
2           YOLO11s + Aug   0.966321  0.964450  0.987207  0.675043
3        YOLO11s + Freeze   0.972619  0.957983  0.986845  0.680756
4  YOLO11s + Aug + Freeze   0.965726  0.966387  0.983915  0.689042

Как мы видим совмещение гипотезы 3 и 4 дало наилучшие результаты. Единственное, в чем проигрывает последняя модель - Precision. Все остальные показтели выше чем у других моделей.

Имплементация собственной модели!

In [24]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import cv2
import os
import numpy as np

device = "cuda" if torch.cuda.is_available() else "cpu"

# DATASET 
class YoloDataset(Dataset):
    def __init__(self, img_dir, label_dir, img_size=224):
        self.img_dir = img_dir
        self.label_dir = label_dir
        self.files = os.listdir(img_dir)
        self.img_size = img_size

    def __len__(self):
        return len(self.files)

    def __getitem__(self, idx):
        img_name = self.files[idx]

        img_path = os.path.join(self.img_dir, img_name)
        label_path = os.path.join(self.label_dir, img_name.replace(".jpg", ".txt"))

        img = cv2.imread(img_path)
        img = cv2.resize(img, (self.img_size, self.img_size))
        img = img / 255.0
        img = torch.tensor(img, dtype=torch.float).permute(2, 0, 1)

        # default: no object
        target = torch.zeros(5)

        if os.path.exists(label_path):
            with open(label_path, "r") as f:
                line = f.readline().strip().split()
                if len(line) == 5:
                    _, x, y, w, h = map(float, line)
                    target = torch.tensor([x, y, w, h, 1.0], dtype=torch.float)

        return img, target


train_dataset = YoloDataset("dataset/images/train", "dataset/labels/train")
val_dataset = YoloDataset("dataset/images/val", "dataset/labels/val")

train_loader = DataLoader(train_dataset, batch_size=8, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=8, shuffle=False)

# MODEL
class SimpleYOLO(nn.Module):
    def __init__(self):
        super().__init__()

        self.backbone = nn.Sequential(
            nn.Conv2d(3, 32, 3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(32, 64, 3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(64, 128, 3, padding=1),
            nn.ReLU(),
            nn.AdaptiveAvgPool2d((1, 1))
        )

        self.head = nn.Linear(128, 5)  # x,y,w,h,obj

    def forward(self, x):
        x = self.backbone(x)
        x = x.view(x.size(0), -1)
        return torch.sigmoid(self.head(x))


model = SimpleYOLO().to(device)

# LOSS
def loss_fn(pred, target):
    box_loss = F.mse_loss(pred[:, :4], target[:, :4])
    obj_loss = F.binary_cross_entropy(pred[:, 4], target[:, 4])
    return box_loss + obj_loss

# IoU
def iou(box1, box2):
    x1, y1, w1, h1 = box1
    x2, y2, w2, h2 = box2

    b1_x1, b1_y1 = x1 - w1/2, y1 - h1/2
    b1_x2, b1_y2 = x1 + w1/2, y1 + h1/2

    b2_x1, b2_y1 = x2 - w2/2, y2 - h2/2
    b2_x2, b2_y2 = x2 + w2/2, y2 + h2/2

    inter_x1 = max(b1_x1, b2_x1)
    inter_y1 = max(b1_y1, b2_y1)
    inter_x2 = min(b1_x2, b2_x2)
    inter_y2 = min(b1_y2, b2_y2)

    inter = max(0, inter_x2 - inter_x1) * max(0, inter_y2 - inter_y1)

    area1 = (b1_x2 - b1_x1) * (b1_y2 - b1_y1)
    area2 = (b2_x2 - b2_x1) * (b2_y2 - b2_y1)

    return inter / (area1 + area2 - inter + 1e-6)

In [25]:
import torch
print(torch.randn(1).cuda())

tensor([0.8591], device='cuda:0')

In [26]:
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

model.train()

for epoch in range(40):
    total_loss = 0

    for imgs, targets in train_loader:
        imgs = imgs.to(device)
        targets = targets.to(device)

        preds = model(imgs)
        loss = loss_fn(preds, targets)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}/40 | Loss: {total_loss:.4f}")

Epoch 1/40 | Loss: 5.9324
Epoch 2/40 | Loss: 1.2309
Epoch 3/40 | Loss: 1.0375
Epoch 4/40 | Loss: 0.9246
Epoch 5/40 | Loss: 0.8999
Epoch 6/40 | Loss: 0.8866
Epoch 7/40 | Loss: 0.9033
Epoch 8/40 | Loss: 0.9101
Epoch 9/40 | Loss: 0.9263
Epoch 10/40 | Loss: 0.9141
Epoch 11/40 | Loss: 0.9445
Epoch 12/40 | Loss: 0.8757
Epoch 13/40 | Loss: 0.9068
Epoch 14/40 | Loss: 0.9278
Epoch 15/40 | Loss: 0.8664
Epoch 16/40 | Loss: 0.8925
Epoch 17/40 | Loss: 0.8623
Epoch 18/40 | Loss: 0.8789
Epoch 19/40 | Loss: 0.8701
Epoch 20/40 | Loss: 0.8697
Epoch 21/40 | Loss: 0.8748
Epoch 22/40 | Loss: 0.8658
Epoch 23/40 | Loss: 0.8742
Epoch 24/40 | Loss: 0.9025
Epoch 25/40 | Loss: 0.8639
Epoch 26/40 | Loss: 0.9075
Epoch 27/40 | Loss: 0.8750
Epoch 28/40 | Loss: 0.8758
Epoch 29/40 | Loss: 0.8750
Epoch 30/40 | Loss: 0.8825
Epoch 31/40 | Loss: 0.8833
Epoch 32/40 | Loss: 0.8656
Epoch 33/40 | Loss: 0.8691
Epoch 34/40 | Loss: 0.8665
Epoch 35/40 | Loss: 0.8556
Epoch 36/40 | Loss: 0.8565
Epoch 37/40 | Loss: 0.8751
Epoch 38/40 | Loss: 0.8635
Epoch 39/40 | Loss: 0.8896
Epoch 40/40 | Loss: 0.8604

In [27]:
def evaluate(model, loader):
    model.eval()

    iou_thresholds = np.linspace(0.5, 0.95, 10)
    aps = []

    with torch.no_grad():
        for t in iou_thresholds:
            tp, fp, fn = 0, 0, 0

            for imgs, targets in loader:
                imgs = imgs.to(device)
                targets = targets.to(device)

                preds = model(imgs)

                for p, gt in zip(preds, targets):
                    if gt[4] == 0:
                        continue

                    iou_score = iou(
                        p[:4].cpu().numpy(),
                        gt[:4].cpu().numpy()
                    )

                    if iou_score >= t:
                        tp += 1
                    else:
                        fp += 1
                        fn += 1

            precision = tp / (tp + fp + 1e-6)
            aps.append(precision)

    mAP50 = aps[0]
    mAP50_95 = np.mean(aps)
    recall = aps[0]

    print("\n===== RESULTS =====")
    print("Precision:", round(aps[0], 4))
    print("Recall:", round(recall, 4))
    print("mAP50:", round(mAP50, 4))
    print("mAP50-95:", round(mAP50_95, 4))

    return {
        "Precision": float(aps[0]),
        "Recall": float(recall),
        "mAP50": float(mAP50),
        "mAP50-95": float(mAP50_95)
    }

In [28]:
metrics = evaluate(model, val_loader)

results.append({
    "Model": "YOLO custom",
    **metrics
})

===== RESULTS =====
Precision: 0.0141
Recall: 0.0141
mAP50: 0.0141
mAP50-95: 0.0028

Ожидаемо самописаня модель показала ужасные результаты. Базовая имплементированная модель имеет крайне ограниченную архитектуру и решает задачу детекции в сильно упрощённой постановке, фактически сводя её к регрессии координат одного объекта на изображении. В модели отсутствуют механизмы, характерные для современных детекторов, такие как якоря, разбиение изображения на сетку или обработка множественных объектов. Из-за этого модель не способна полноценно интерпретировать сцену и корректно локализовать объекты.

Первую гипотезу мы не можем проверить по очевидной причине - мы не можем использовать более мощную модель, ибо ее не существует.

Третья гипотеза также не применяется, поскольку входные данные уже приведены к фиксированному размеру и формату, и изменение разрешения или структуры данных нарушило бы единые условия сравнения между экспериментами. Поэтому дальнейший анализ проводится только для второй гипотезы, как единственного корректного варианта изменения модели без изменения постановки задачи и данных:

In [29]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import cv2
import os
import numpy as np

device = "cuda" if torch.cuda.is_available() else "cpu"

# DATASET
class YoloDataset(Dataset):
    def __init__(self, img_dir, label_dir, img_size=224):
        self.img_dir = img_dir
        self.label_dir = label_dir
        self.files = os.listdir(img_dir)
        self.img_size = img_size

    def __len__(self):
        return len(self.files)

    def __getitem__(self, idx):
        img_name = self.files[idx]

        img_path = os.path.join(self.img_dir, img_name)
        label_path = os.path.join(self.label_dir, img_name.replace(".jpg", ".txt"))

        img = cv2.imread(img_path)
        img = cv2.resize(img, (self.img_size, self.img_size))
        img = img / 255.0
        img = torch.tensor(img, dtype=torch.float32).permute(2, 0, 1)

        target = torch.zeros(5)

        if os.path.exists(label_path):
            with open(label_path, "r") as f:
                line = f.readline().strip().split()
                if len(line) == 5:
                    _, x, y, w, h = map(float, line)
                    target = torch.tensor([x, y, w, h, 1.0], dtype=torch.float32)

        return img, target


train_dataset = YoloDataset("dataset/images/train", "dataset/labels/train")
val_dataset = YoloDataset("dataset/images/val", "dataset/labels/val")

train_loader = DataLoader(train_dataset, batch_size=8, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=8, shuffle=False)

# MODEL
class SimpleYOLO_H2(nn.Module):
    def __init__(self):
        super().__init__()

        self.backbone = nn.Sequential(
            nn.Conv2d(3, 32, 3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(32, 64, 3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(64, 128, 3, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(),

            nn.Conv2d(128, 256, 3, padding=1),
            nn.BatchNorm2d(256),
            nn.ReLU(),

            nn.AdaptiveAvgPool2d((1, 1))
        )

        self.head = nn.Sequential(
            nn.Linear(256, 128),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(128, 5)
        )

    def forward(self, x):
        x = self.backbone(x)
        x = x.view(x.size(0), -1)
        return torch.sigmoid(self.head(x))


model = SimpleYOLO_H2().to(device)

# LOSS
def loss_fn(pred, target):
    box_loss = F.mse_loss(pred[:, :4], target[:, :4])
    obj_loss = F.binary_cross_entropy(pred[:, 4], target[:, 4])
    return box_loss + obj_loss

# IOU
def iou(box1, box2):
    x1, y1, w1, h1 = box1
    x2, y2, w2, h2 = box2

    b1_x1, b1_y1 = x1 - w1/2, y1 - h1/2
    b1_x2, b1_y2 = x1 + w1/2, y1 + h1/2

    b2_x1, b2_y1 = x2 - w2/2, y2 - h2/2
    b2_x2, b2_y2 = x2 + w2/2, y2 + h2/2

    inter_x1 = max(b1_x1, b2_x1)
    inter_y1 = max(b1_y1, b2_y1)
    inter_x2 = min(b1_x2, b2_x2)
    inter_y2 = min(b1_y2, b2_y2)

    inter = max(0, inter_x2 - inter_x1) * max(0, inter_y2 - inter_y1)

    area1 = (b1_x2 - b1_x1) * (b1_y2 - b1_y1)
    area2 = (b2_x2 - b2_x1) * (b2_y2 - b2_y1)

    return inter / (area1 + area2 - inter + 1e-6)

In [30]:
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

model.train()

for epoch in range(40):
    total_loss = 0.0

    for imgs, targets in train_loader:
        imgs = imgs.to(device)
        targets = targets.to(device)

        preds = model(imgs)
        loss = loss_fn(preds, targets)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}/40 | Loss: {total_loss:.4f}")

Epoch 1/40 | Loss: 4.5139
Epoch 2/40 | Loss: 1.1659
Epoch 3/40 | Loss: 1.0466
Epoch 4/40 | Loss: 0.9984
Epoch 5/40 | Loss: 1.0082
Epoch 6/40 | Loss: 0.9313
Epoch 7/40 | Loss: 0.9595
Epoch 8/40 | Loss: 0.9259
Epoch 9/40 | Loss: 0.8772
Epoch 10/40 | Loss: 0.8814
Epoch 11/40 | Loss: 0.8932
Epoch 12/40 | Loss: 0.8622
Epoch 13/40 | Loss: 0.8643
Epoch 14/40 | Loss: 0.8599
Epoch 15/40 | Loss: 0.8954
Epoch 16/40 | Loss: 0.8495
Epoch 17/40 | Loss: 0.8346
Epoch 18/40 | Loss: 0.8994
Epoch 19/40 | Loss: 0.8284
Epoch 20/40 | Loss: 0.8576
Epoch 21/40 | Loss: 0.8348
Epoch 22/40 | Loss: 0.8093
Epoch 23/40 | Loss: 0.8071
Epoch 24/40 | Loss: 0.8207
Epoch 25/40 | Loss: 0.8314
Epoch 26/40 | Loss: 0.8256
Epoch 27/40 | Loss: 0.8622
Epoch 28/40 | Loss: 0.8577
Epoch 29/40 | Loss: 0.8208
Epoch 30/40 | Loss: 0.8233
Epoch 31/40 | Loss: 0.8153
Epoch 32/40 | Loss: 0.8461
Epoch 33/40 | Loss: 0.8587
Epoch 34/40 | Loss: 0.8141
Epoch 35/40 | Loss: 0.8239
Epoch 36/40 | Loss: 0.8288
Epoch 37/40 | Loss: 0.8079
Epoch 38/40 | Loss: 0.8538
Epoch 39/40 | Loss: 0.8171
Epoch 40/40 | Loss: 0.8266

In [31]:
import numpy as np
import torch

def evaluate(model, loader):
    model.eval()

    iou_thresholds = np.linspace(0.5, 0.95, 10)
    aps = []

    with torch.no_grad():
        for t in iou_thresholds:
            tp, fp = 0, 0

            for imgs, targets in loader:
                imgs = imgs.to(device)
                targets = targets.to(device)

                preds = model(imgs)

                for p, gt in zip(preds, targets):
                    if gt[4].item() == 0:
                        continue

                    iou_score = iou(
                        p[:4].detach().cpu().numpy(),
                        gt[:4].detach().cpu().numpy()
                    )

                    if iou_score >= t:
                        tp += 1
                    else:
                        fp += 1

            precision = tp / (tp + fp + 1e-6)
            aps.append(precision)

    mAP50 = aps[0]
    mAP50_95 = float(np.mean(aps))
    recall = aps[0]

    print("\n===== HYPOTHESIS 2 RESULTS =====")
    print("Precision:", round(mAP50, 4))
    print("Recall:", round(recall, 4))
    print("mAP50:", round(mAP50, 4))
    print("mAP50-95:", round(mAP50_95, 4))

    return {
        "Precision": float(mAP50),
        "Recall": float(recall),
        "mAP50": float(mAP50),
        "mAP50-95": float(mAP50_95)
    }

In [32]:
metrics = evaluate(model, val_loader)

results.append({
    "Model": "SimpleYOLO + Hypothesis 2",
    **metrics
})

===== HYPOTHESIS 2 RESULTS =====
Precision: 0.0845
Recall: 0.0845
mAP50: 0.0845
mAP50-95: 0.0324

Во второй конфигурации модель была усложнена за счёт увеличения глубины сверточной части сети, что теоретически должно улучшать способность извлекать признаки. И мы действительно увидели небольшое улучшение.

# Смотрим полный итоговые результаты:

In [33]:
import pandas as pd

df = pd.DataFrame(results)
df

                       Model  Precision    Recall     mAP50  mAP50-95
0                    YOLO11n   0.984121  0.949580  0.973670  0.654472
1                    YOLO11s   0.958292  0.965390  0.976780  0.679280
2              YOLO11s + Aug   0.966321  0.964450  0.987207  0.675043
3           YOLO11s + Freeze   0.972619  0.957983  0.986845  0.680756
4     YOLO11s + Aug + Freeze   0.965726  0.966387  0.983915  0.689042
5                YOLO custom   0.014085  0.014085  0.014085  0.002817
6  SimpleYOLO + Hypothesis 2   0.084507  0.084507  0.084507  0.032394

# Заключение

В ходе экспериментов с YOLO11 были получены результаты для нескольких конфигураций модели, включая базовые версии и варианты с применением техник улучшенного бейзлайна. В целом можно отметить, что все версии YOLO демонстрируют высокое качество детекции по метрикам Precision, Recall и mAP50, что говорит о стабильной работе модели на данном наборе данных и хорошей способности находить и классифицировать объекты.

При сравнении различных конфигураций видно, что базовая модель YOLO11n уже обеспечивает достаточно высокий уровень качества, однако переход к более крупной версии YOLO11s даёт небольшой прирост по большинству метрик, что подтверждает влияние увеличения ёмкости модели на качество детекции.

Применение аугментаций и заморозки части слоёв приводит к незначительным колебаниям результатов, при этом наиболее стабильные и сбалансированные показатели наблюдаются у комбинации этих подходов. В этой конфигурации достигается наилучшее значение метрики mAP50–95, что указывает на более качественную локализацию объектов при разных порогах IoU и более устойчивую работу модели в сложных случаях.

Таким образом, можно сделать вывод, что основное улучшение качества достигается не за счёт одной конкретной техники, а за счёт их комбинирования, при этом эффект от отдельных модификаций является умеренным. Модель YOLO в целом показывает высокую устойчивость к изменениям конфигурации, а улучшения носят инкрементальный характер, а не радикальный.